/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetExpoEventResponse } from '../../models/get-expo-event-response';

export interface ExpoEventControllerCloseEventV1$Params {
  id: number;
}

export function expoEventControllerCloseEventV1(http: HttpClient, rootUrl: string, params: ExpoEventControllerCloseEventV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetExpoEventResponse>> {
  const rb = new RequestBuilder(rootUrl, expoEventControllerCloseEventV1.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetExpoEventResponse>;
    })
  );
}

expoEventControllerCloseEventV1.PATH = '/api/v1/expo-event/{id}/close';
