/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetExpoEventResponse } from '../../models/get-expo-event-response';
import { UpdateExpoEventDto } from '../../models/update-expo-event-dto';

export interface ExpoEventControllerUpdateV1$Params {
  id: string;
      body: UpdateExpoEventDto
}

export function expoEventControllerUpdateV1(http: HttpClient, rootUrl: string, params: ExpoEventControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetExpoEventResponse>> {
  const rb = new RequestBuilder(rootUrl, expoEventControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetExpoEventResponse>;
    })
  );
}

expoEventControllerUpdateV1.PATH = '/api/v1/expo-event/{id}';
