/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetExpoEventResponse } from '../../models/get-expo-event-response';

export interface ExpoEventControllerGetAllExpoEventsV1$Params {

/**
 * The name of the expo event
 */
  name?: string;

/**
 * The place of the expo event
 */
  place?: string;

/**
 * The town of the expo event
 */
  townId?: number;

/**
 * The start date of the expo event
 */
  startDate?: string;

/**
 * The end date of the expo event
 */
  endDate?: string;

/**
 * The owner name of the expo event
 */
  ownerName?: string;

/**
 * The status of the expo event
 */
  status?: 'PLANNED' | 'IN_PROGRESS' | 'CLOSED';

/**
 * The page number
 */
  page?: number;

/**
 * The number of items per page
 */
  limit?: number;
}

export function expoEventControllerGetAllExpoEventsV1(http: HttpClient, rootUrl: string, params?: ExpoEventControllerGetAllExpoEventsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetExpoEventResponse>> {
  const rb = new RequestBuilder(rootUrl, expoEventControllerGetAllExpoEventsV1.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('place', params.place, {});
    rb.query('townId', params.townId, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('ownerName', params.ownerName, {});
    rb.query('status', params.status, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetExpoEventResponse>;
    })
  );
}

expoEventControllerGetAllExpoEventsV1.PATH = '/api/v1/expo-event';
