/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { authControllerDeleteAccountV1 } from '../fn/auth/auth-controller-delete-account-v-1';
import { AuthControllerDeleteAccountV1$Params } from '../fn/auth/auth-controller-delete-account-v-1';
import { authControllerGetCurrentUserV1 } from '../fn/auth/auth-controller-get-current-user-v-1';
import { AuthControllerGetCurrentUserV1$Params } from '../fn/auth/auth-controller-get-current-user-v-1';
import { authControllerLoginV1 } from '../fn/auth/auth-controller-login-v-1';
import { AuthControllerLoginV1$Params } from '../fn/auth/auth-controller-login-v-1';
import { authControllerRefreshTokenV1 } from '../fn/auth/auth-controller-refresh-token-v-1';
import { AuthControllerRefreshTokenV1$Params } from '../fn/auth/auth-controller-refresh-token-v-1';
import { LoginResponseDto } from '../models/login-response-dto';
import { RefreshTokenResponseDto } from '../models/refresh-token-response-dto';


/**
 * Authentication endpoints
 */
@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `authControllerLoginV1()` */
  static readonly AuthControllerLoginV1Path = '/api/v1/auth/login';

  /**
   * Login user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerLoginV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerLoginV1$Response(params: AuthControllerLoginV1$Params, context?: HttpContext): Observable<StrictHttpResponse<LoginResponseDto>> {
    return authControllerLoginV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Login user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerLoginV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerLoginV1(params: AuthControllerLoginV1$Params, context?: HttpContext): Observable<LoginResponseDto> {
    return this.authControllerLoginV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<LoginResponseDto>): LoginResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerGetCurrentUserV1()` */
  static readonly AuthControllerGetCurrentUserV1Path = '/api/v1/auth/me';

  /**
   * Get current user information.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerGetCurrentUserV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerGetCurrentUserV1$Response(params?: AuthControllerGetCurrentUserV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authControllerGetCurrentUserV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current user information.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerGetCurrentUserV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerGetCurrentUserV1(params?: AuthControllerGetCurrentUserV1$Params, context?: HttpContext): Observable<void> {
    return this.authControllerGetCurrentUserV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authControllerRefreshTokenV1()` */
  static readonly AuthControllerRefreshTokenV1Path = '/api/v1/auth/refresh-token';

  /**
   * Refresh access token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerRefreshTokenV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRefreshTokenV1$Response(params: AuthControllerRefreshTokenV1$Params, context?: HttpContext): Observable<StrictHttpResponse<RefreshTokenResponseDto>> {
    return authControllerRefreshTokenV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Refresh access token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerRefreshTokenV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRefreshTokenV1(params: AuthControllerRefreshTokenV1$Params, context?: HttpContext): Observable<RefreshTokenResponseDto> {
    return this.authControllerRefreshTokenV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<RefreshTokenResponseDto>): RefreshTokenResponseDto => r.body)
    );
  }

  /** Path part for operation `authControllerDeleteAccountV1()` */
  static readonly AuthControllerDeleteAccountV1Path = '/api/v1/auth/delete';

  /**
   * Delete current user account.
   *
   * Soft delete the authenticated user account. Sets deleted_at so the user can no longer log in.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerDeleteAccountV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerDeleteAccountV1$Response(params?: AuthControllerDeleteAccountV1$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
}>> {
    return authControllerDeleteAccountV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete current user account.
   *
   * Soft delete the authenticated user account. Sets deleted_at so the user can no longer log in.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerDeleteAccountV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerDeleteAccountV1(params?: AuthControllerDeleteAccountV1$Params, context?: HttpContext): Observable<{
'message'?: string;
}> {
    return this.authControllerDeleteAccountV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'message'?: string;
}>): {
'message'?: string;
} => r.body)
    );
  }

}
