/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Consumable } from '../models/consumable';
import { consumableControllerCreateV1 } from '../fn/consumable/consumable-controller-create-v-1';
import { ConsumableControllerCreateV1$Params } from '../fn/consumable/consumable-controller-create-v-1';
import { consumableControllerGetAllConsumablesV1 } from '../fn/consumable/consumable-controller-get-all-consumables-v-1';
import { ConsumableControllerGetAllConsumablesV1$Params } from '../fn/consumable/consumable-controller-get-all-consumables-v-1';
import { consumableControllerRemoveV1 } from '../fn/consumable/consumable-controller-remove-v-1';
import { ConsumableControllerRemoveV1$Params } from '../fn/consumable/consumable-controller-remove-v-1';
import { consumableControllerUpdateV1 } from '../fn/consumable/consumable-controller-update-v-1';
import { ConsumableControllerUpdateV1$Params } from '../fn/consumable/consumable-controller-update-v-1';
import { GetConsumableResponse } from '../models/get-consumable-response';

@Injectable({ providedIn: 'root' })
export class ConsumableService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `consumableControllerGetAllConsumablesV1()` */
  static readonly ConsumableControllerGetAllConsumablesV1Path = '/api/v1/consumable';

  /**
   * Get all consumables.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `consumableControllerGetAllConsumablesV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  consumableControllerGetAllConsumablesV1$Response(params?: ConsumableControllerGetAllConsumablesV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetConsumableResponse>>> {
    return consumableControllerGetAllConsumablesV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all consumables.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `consumableControllerGetAllConsumablesV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  consumableControllerGetAllConsumablesV1(params?: ConsumableControllerGetAllConsumablesV1$Params, context?: HttpContext): Observable<Array<GetConsumableResponse>> {
    return this.consumableControllerGetAllConsumablesV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetConsumableResponse>>): Array<GetConsumableResponse> => r.body)
    );
  }

  /** Path part for operation `consumableControllerCreateV1()` */
  static readonly ConsumableControllerCreateV1Path = '/api/v1/consumable';

  /**
   * Create a new consumable.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `consumableControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  consumableControllerCreateV1$Response(params: ConsumableControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Consumable>> {
    return consumableControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new consumable.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `consumableControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  consumableControllerCreateV1(params: ConsumableControllerCreateV1$Params, context?: HttpContext): Observable<Consumable> {
    return this.consumableControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Consumable>): Consumable => r.body)
    );
  }

  /** Path part for operation `consumableControllerRemoveV1()` */
  static readonly ConsumableControllerRemoveV1Path = '/api/v1/consumable/{id}';

  /**
   * Delete a consumable.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `consumableControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  consumableControllerRemoveV1$Response(params: ConsumableControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Consumable>> {
    return consumableControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a consumable.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `consumableControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  consumableControllerRemoveV1(params: ConsumableControllerRemoveV1$Params, context?: HttpContext): Observable<Consumable> {
    return this.consumableControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Consumable>): Consumable => r.body)
    );
  }

  /** Path part for operation `consumableControllerUpdateV1()` */
  static readonly ConsumableControllerUpdateV1Path = '/api/v1/consumable/{id}';

  /**
   * Update a consumable.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `consumableControllerUpdateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  consumableControllerUpdateV1$Response(params: ConsumableControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Consumable>> {
    return consumableControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a consumable.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `consumableControllerUpdateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  consumableControllerUpdateV1(params: ConsumableControllerUpdateV1$Params, context?: HttpContext): Observable<Consumable> {
    return this.consumableControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Consumable>): Consumable => r.body)
    );
  }

}
