/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { countryControllerCreateV1 } from '../fn/country/country-controller-create-v-1';
import { CountryControllerCreateV1$Params } from '../fn/country/country-controller-create-v-1';
import { countryControllerFindAllV1 } from '../fn/country/country-controller-find-all-v-1';
import { CountryControllerFindAllV1$Params } from '../fn/country/country-controller-find-all-v-1';
import { countryControllerFindOneV1 } from '../fn/country/country-controller-find-one-v-1';
import { CountryControllerFindOneV1$Params } from '../fn/country/country-controller-find-one-v-1';
import { countryControllerRemoveV1 } from '../fn/country/country-controller-remove-v-1';
import { CountryControllerRemoveV1$Params } from '../fn/country/country-controller-remove-v-1';
import { countryControllerUpdateV1 } from '../fn/country/country-controller-update-v-1';
import { CountryControllerUpdateV1$Params } from '../fn/country/country-controller-update-v-1';
import { CountryResponseDto } from '../models/country-response-dto';

@Injectable({ providedIn: 'root' })
export class CountryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `countryControllerFindAllV1()` */
  static readonly CountryControllerFindAllV1Path = '/api/v1/country';

  /**
   * Get all countries.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `countryControllerFindAllV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  countryControllerFindAllV1$Response(params?: CountryControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<CountryResponseDto>> {
    return countryControllerFindAllV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all countries.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `countryControllerFindAllV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  countryControllerFindAllV1(params?: CountryControllerFindAllV1$Params, context?: HttpContext): Observable<CountryResponseDto> {
    return this.countryControllerFindAllV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<CountryResponseDto>): CountryResponseDto => r.body)
    );
  }

  /** Path part for operation `countryControllerCreateV1()` */
  static readonly CountryControllerCreateV1Path = '/api/v1/country';

  /**
   * Create a new country.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `countryControllerCreateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  countryControllerCreateV1$Response(params: CountryControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<CountryResponseDto>> {
    return countryControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new country.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `countryControllerCreateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  countryControllerCreateV1(params: CountryControllerCreateV1$Params, context?: HttpContext): Observable<CountryResponseDto> {
    return this.countryControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<CountryResponseDto>): CountryResponseDto => r.body)
    );
  }

  /** Path part for operation `countryControllerFindOneV1()` */
  static readonly CountryControllerFindOneV1Path = '/api/v1/country/{id}';

  /**
   * Get a country by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `countryControllerFindOneV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  countryControllerFindOneV1$Response(params: CountryControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<CountryResponseDto>> {
    return countryControllerFindOneV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a country by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `countryControllerFindOneV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  countryControllerFindOneV1(params: CountryControllerFindOneV1$Params, context?: HttpContext): Observable<CountryResponseDto> {
    return this.countryControllerFindOneV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<CountryResponseDto>): CountryResponseDto => r.body)
    );
  }

  /** Path part for operation `countryControllerRemoveV1()` */
  static readonly CountryControllerRemoveV1Path = '/api/v1/country/{id}';

  /**
   * Delete a country.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `countryControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  countryControllerRemoveV1$Response(params: CountryControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return countryControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a country.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `countryControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  countryControllerRemoveV1(params: CountryControllerRemoveV1$Params, context?: HttpContext): Observable<void> {
    return this.countryControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `countryControllerUpdateV1()` */
  static readonly CountryControllerUpdateV1Path = '/api/v1/country/{id}';

  /**
   * Update a country.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `countryControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  countryControllerUpdateV1$Response(params: CountryControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<CountryResponseDto>> {
    return countryControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a country.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `countryControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  countryControllerUpdateV1(params: CountryControllerUpdateV1$Params, context?: HttpContext): Observable<CountryResponseDto> {
    return this.countryControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<CountryResponseDto>): CountryResponseDto => r.body)
    );
  }

}
