/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { documentControllerCreateV1 } from '../fn/document/document-controller-create-v-1';
import { DocumentControllerCreateV1$Params } from '../fn/document/document-controller-create-v-1';
import { documentControllerFindByEntityV1 } from '../fn/document/document-controller-find-by-entity-v-1';
import { DocumentControllerFindByEntityV1$Params } from '../fn/document/document-controller-find-by-entity-v-1';
import { documentControllerFindOneV1 } from '../fn/document/document-controller-find-one-v-1';
import { DocumentControllerFindOneV1$Params } from '../fn/document/document-controller-find-one-v-1';
import { documentControllerGetAllDocumentsV1 } from '../fn/document/document-controller-get-all-documents-v-1';
import { DocumentControllerGetAllDocumentsV1$Params } from '../fn/document/document-controller-get-all-documents-v-1';
import { documentControllerRemoveV1 } from '../fn/document/document-controller-remove-v-1';
import { DocumentControllerRemoveV1$Params } from '../fn/document/document-controller-remove-v-1';
import { documentControllerUpdateV1 } from '../fn/document/document-controller-update-v-1';
import { DocumentControllerUpdateV1$Params } from '../fn/document/document-controller-update-v-1';
import { GetDocumentResponse } from '../models/get-document-response';

@Injectable({ providedIn: 'root' })
export class DocumentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `documentControllerGetAllDocumentsV1()` */
  static readonly DocumentControllerGetAllDocumentsV1Path = '/api/v1/document';

  /**
   * Get all documents with pagination and filtering.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentControllerGetAllDocumentsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentControllerGetAllDocumentsV1$Response(params?: DocumentControllerGetAllDocumentsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetDocumentResponse>>> {
    return documentControllerGetAllDocumentsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all documents with pagination and filtering.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentControllerGetAllDocumentsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentControllerGetAllDocumentsV1(params?: DocumentControllerGetAllDocumentsV1$Params, context?: HttpContext): Observable<Array<GetDocumentResponse>> {
    return this.documentControllerGetAllDocumentsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetDocumentResponse>>): Array<GetDocumentResponse> => r.body)
    );
  }

  /** Path part for operation `documentControllerCreateV1()` */
  static readonly DocumentControllerCreateV1Path = '/api/v1/document';

  /**
   * Create a new document (upload file and attach to an entity).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  documentControllerCreateV1$Response(params: DocumentControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetDocumentResponse>> {
    return documentControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new document (upload file and attach to an entity).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  documentControllerCreateV1(params: DocumentControllerCreateV1$Params, context?: HttpContext): Observable<GetDocumentResponse> {
    return this.documentControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetDocumentResponse>): GetDocumentResponse => r.body)
    );
  }

  /** Path part for operation `documentControllerFindByEntityV1()` */
  static readonly DocumentControllerFindByEntityV1Path = '/api/v1/document/entity/{entityType}/{entityId}';

  /**
   * Get all documents for a specific entity.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentControllerFindByEntityV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentControllerFindByEntityV1$Response(params: DocumentControllerFindByEntityV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetDocumentResponse>>> {
    return documentControllerFindByEntityV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all documents for a specific entity.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentControllerFindByEntityV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentControllerFindByEntityV1(params: DocumentControllerFindByEntityV1$Params, context?: HttpContext): Observable<Array<GetDocumentResponse>> {
    return this.documentControllerFindByEntityV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetDocumentResponse>>): Array<GetDocumentResponse> => r.body)
    );
  }

  /** Path part for operation `documentControllerFindOneV1()` */
  static readonly DocumentControllerFindOneV1Path = '/api/v1/document/{id}';

  /**
   * Get a document by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentControllerFindOneV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentControllerFindOneV1$Response(params: DocumentControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetDocumentResponse>> {
    return documentControllerFindOneV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a document by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentControllerFindOneV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentControllerFindOneV1(params: DocumentControllerFindOneV1$Params, context?: HttpContext): Observable<GetDocumentResponse> {
    return this.documentControllerFindOneV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetDocumentResponse>): GetDocumentResponse => r.body)
    );
  }

  /** Path part for operation `documentControllerRemoveV1()` */
  static readonly DocumentControllerRemoveV1Path = '/api/v1/document/{id}';

  /**
   * Delete a document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentControllerRemoveV1$Response(params: DocumentControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentControllerRemoveV1(params: DocumentControllerRemoveV1$Params, context?: HttpContext): Observable<void> {
    return this.documentControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentControllerUpdateV1()` */
  static readonly DocumentControllerUpdateV1Path = '/api/v1/document/{id}';

  /**
   * Update a document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentControllerUpdateV1$Response(params: DocumentControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetDocumentResponse>> {
    return documentControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentControllerUpdateV1(params: DocumentControllerUpdateV1$Params, context?: HttpContext): Observable<GetDocumentResponse> {
    return this.documentControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetDocumentResponse>): GetDocumentResponse => r.body)
    );
  }

}
