/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { expoEventControllerCloseEventV1 } from '../fn/expo-event/expo-event-controller-close-event-v-1';
import { ExpoEventControllerCloseEventV1$Params } from '../fn/expo-event/expo-event-controller-close-event-v-1';
import { expoEventControllerCreateV1 } from '../fn/expo-event/expo-event-controller-create-v-1';
import { ExpoEventControllerCreateV1$Params } from '../fn/expo-event/expo-event-controller-create-v-1';
import { expoEventControllerGetAllExpoEventsV1 } from '../fn/expo-event/expo-event-controller-get-all-expo-events-v-1';
import { ExpoEventControllerGetAllExpoEventsV1$Params } from '../fn/expo-event/expo-event-controller-get-all-expo-events-v-1';
import { expoEventControllerRemoveV1 } from '../fn/expo-event/expo-event-controller-remove-v-1';
import { ExpoEventControllerRemoveV1$Params } from '../fn/expo-event/expo-event-controller-remove-v-1';
import { expoEventControllerUpdateV1 } from '../fn/expo-event/expo-event-controller-update-v-1';
import { ExpoEventControllerUpdateV1$Params } from '../fn/expo-event/expo-event-controller-update-v-1';
import { GetExpoEventResponse } from '../models/get-expo-event-response';

@Injectable({ providedIn: 'root' })
export class ExpoEventService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `expoEventControllerGetAllExpoEventsV1()` */
  static readonly ExpoEventControllerGetAllExpoEventsV1Path = '/api/v1/expo-event';

  /**
   * See all expo events.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `expoEventControllerGetAllExpoEventsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  expoEventControllerGetAllExpoEventsV1$Response(params?: ExpoEventControllerGetAllExpoEventsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetExpoEventResponse>> {
    return expoEventControllerGetAllExpoEventsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * See all expo events.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `expoEventControllerGetAllExpoEventsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  expoEventControllerGetAllExpoEventsV1(params?: ExpoEventControllerGetAllExpoEventsV1$Params, context?: HttpContext): Observable<GetExpoEventResponse> {
    return this.expoEventControllerGetAllExpoEventsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetExpoEventResponse>): GetExpoEventResponse => r.body)
    );
  }

  /** Path part for operation `expoEventControllerCreateV1()` */
  static readonly ExpoEventControllerCreateV1Path = '/api/v1/expo-event';

  /**
   * Create a new expo event.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `expoEventControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  expoEventControllerCreateV1$Response(params: ExpoEventControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetExpoEventResponse>> {
    return expoEventControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new expo event.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `expoEventControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  expoEventControllerCreateV1(params: ExpoEventControllerCreateV1$Params, context?: HttpContext): Observable<GetExpoEventResponse> {
    return this.expoEventControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetExpoEventResponse>): GetExpoEventResponse => r.body)
    );
  }

  /** Path part for operation `expoEventControllerRemoveV1()` */
  static readonly ExpoEventControllerRemoveV1Path = '/api/v1/expo-event/{id}';

  /**
   * Delete an expo event.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `expoEventControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  expoEventControllerRemoveV1$Response(params: ExpoEventControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetExpoEventResponse>> {
    return expoEventControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete an expo event.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `expoEventControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  expoEventControllerRemoveV1(params: ExpoEventControllerRemoveV1$Params, context?: HttpContext): Observable<GetExpoEventResponse> {
    return this.expoEventControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetExpoEventResponse>): GetExpoEventResponse => r.body)
    );
  }

  /** Path part for operation `expoEventControllerUpdateV1()` */
  static readonly ExpoEventControllerUpdateV1Path = '/api/v1/expo-event/{id}';

  /**
   * Update an expo event.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `expoEventControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  expoEventControllerUpdateV1$Response(params: ExpoEventControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetExpoEventResponse>> {
    return expoEventControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update an expo event.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `expoEventControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  expoEventControllerUpdateV1(params: ExpoEventControllerUpdateV1$Params, context?: HttpContext): Observable<GetExpoEventResponse> {
    return this.expoEventControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetExpoEventResponse>): GetExpoEventResponse => r.body)
    );
  }

  /** Path part for operation `expoEventControllerCloseEventV1()` */
  static readonly ExpoEventControllerCloseEventV1Path = '/api/v1/expo-event/{id}/close';

  /**
   * Close an expo event (validates all items returned and inspected).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `expoEventControllerCloseEventV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  expoEventControllerCloseEventV1$Response(params: ExpoEventControllerCloseEventV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetExpoEventResponse>> {
    return expoEventControllerCloseEventV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Close an expo event (validates all items returned and inspected).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `expoEventControllerCloseEventV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  expoEventControllerCloseEventV1(params: ExpoEventControllerCloseEventV1$Params, context?: HttpContext): Observable<GetExpoEventResponse> {
    return this.expoEventControllerCloseEventV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetExpoEventResponse>): GetExpoEventResponse => r.body)
    );
  }

}
