/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Inspection } from '../models/inspection';
import { inspectionControllerCreateV1 } from '../fn/inspection/inspection-controller-create-v-1';
import { InspectionControllerCreateV1$Params } from '../fn/inspection/inspection-controller-create-v-1';
import { inspectionControllerFindAllV1 } from '../fn/inspection/inspection-controller-find-all-v-1';
import { InspectionControllerFindAllV1$Params } from '../fn/inspection/inspection-controller-find-all-v-1';
import { inspectionControllerFindOneV1 } from '../fn/inspection/inspection-controller-find-one-v-1';
import { InspectionControllerFindOneV1$Params } from '../fn/inspection/inspection-controller-find-one-v-1';
import { inspectionControllerRemoveV1 } from '../fn/inspection/inspection-controller-remove-v-1';
import { InspectionControllerRemoveV1$Params } from '../fn/inspection/inspection-controller-remove-v-1';
import { inspectionControllerUpdateV1 } from '../fn/inspection/inspection-controller-update-v-1';
import { InspectionControllerUpdateV1$Params } from '../fn/inspection/inspection-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class InspectionService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `inspectionControllerFindAllV1()` */
  static readonly InspectionControllerFindAllV1Path = '/api/v1/inspection';

  /**
   * Get all inspections with pagination and filtering by product ID and result.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inspectionControllerFindAllV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  inspectionControllerFindAllV1$Response(params?: InspectionControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Inspection>>> {
    return inspectionControllerFindAllV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all inspections with pagination and filtering by product ID and result.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inspectionControllerFindAllV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inspectionControllerFindAllV1(params?: InspectionControllerFindAllV1$Params, context?: HttpContext): Observable<Array<Inspection>> {
    return this.inspectionControllerFindAllV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Inspection>>): Array<Inspection> => r.body)
    );
  }

  /** Path part for operation `inspectionControllerCreateV1()` */
  static readonly InspectionControllerCreateV1Path = '/api/v1/inspection';

  /**
   * Create a new inspection (automatically updates product status based on result).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inspectionControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inspectionControllerCreateV1$Response(params: InspectionControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Inspection>> {
    return inspectionControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new inspection (automatically updates product status based on result).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inspectionControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  inspectionControllerCreateV1(params: InspectionControllerCreateV1$Params, context?: HttpContext): Observable<Inspection> {
    return this.inspectionControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Inspection>): Inspection => r.body)
    );
  }

  /** Path part for operation `inspectionControllerFindOneV1()` */
  static readonly InspectionControllerFindOneV1Path = '/api/v1/inspection/{id}';

  /**
   * Get an inspection by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inspectionControllerFindOneV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  inspectionControllerFindOneV1$Response(params: InspectionControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Inspection>> {
    return inspectionControllerFindOneV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get an inspection by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inspectionControllerFindOneV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inspectionControllerFindOneV1(params: InspectionControllerFindOneV1$Params, context?: HttpContext): Observable<Inspection> {
    return this.inspectionControllerFindOneV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Inspection>): Inspection => r.body)
    );
  }

  /** Path part for operation `inspectionControllerRemoveV1()` */
  static readonly InspectionControllerRemoveV1Path = '/api/v1/inspection/{id}';

  /**
   * Delete an inspection.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inspectionControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  inspectionControllerRemoveV1$Response(params: InspectionControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return inspectionControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete an inspection.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inspectionControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  inspectionControllerRemoveV1(params: InspectionControllerRemoveV1$Params, context?: HttpContext): Observable<void> {
    return this.inspectionControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `inspectionControllerUpdateV1()` */
  static readonly InspectionControllerUpdateV1Path = '/api/v1/inspection/{id}';

  /**
   * Update an inspection (updates product status if result changes).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inspectionControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inspectionControllerUpdateV1$Response(params: InspectionControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Inspection>> {
    return inspectionControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update an inspection (updates product status if result changes).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inspectionControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inspectionControllerUpdateV1(params: InspectionControllerUpdateV1$Params, context?: HttpContext): Observable<Inspection> {
    return this.inspectionControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Inspection>): Inspection => r.body)
    );
  }

}
