/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Location } from '../models/location';
import { locationControllerCreateV1 } from '../fn/location/location-controller-create-v-1';
import { LocationControllerCreateV1$Params } from '../fn/location/location-controller-create-v-1';
import { locationControllerGetAllLocationsV1 } from '../fn/location/location-controller-get-all-locations-v-1';
import { LocationControllerGetAllLocationsV1$Params } from '../fn/location/location-controller-get-all-locations-v-1';
import { locationControllerRemoveV1 } from '../fn/location/location-controller-remove-v-1';
import { LocationControllerRemoveV1$Params } from '../fn/location/location-controller-remove-v-1';
import { locationControllerUpdateV1 } from '../fn/location/location-controller-update-v-1';
import { LocationControllerUpdateV1$Params } from '../fn/location/location-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class LocationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `locationControllerGetAllLocationsV1()` */
  static readonly LocationControllerGetAllLocationsV1Path = '/api/v1/location';

  /**
   * Get all locations.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `locationControllerGetAllLocationsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  locationControllerGetAllLocationsV1$Response(params?: LocationControllerGetAllLocationsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Location>>> {
    return locationControllerGetAllLocationsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all locations.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `locationControllerGetAllLocationsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  locationControllerGetAllLocationsV1(params?: LocationControllerGetAllLocationsV1$Params, context?: HttpContext): Observable<Array<Location>> {
    return this.locationControllerGetAllLocationsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Location>>): Array<Location> => r.body)
    );
  }

  /** Path part for operation `locationControllerCreateV1()` */
  static readonly LocationControllerCreateV1Path = '/api/v1/location';

  /**
   * Create a new location.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `locationControllerCreateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  locationControllerCreateV1$Response(params: LocationControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Location>> {
    return locationControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new location.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `locationControllerCreateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  locationControllerCreateV1(params: LocationControllerCreateV1$Params, context?: HttpContext): Observable<Location> {
    return this.locationControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Location>): Location => r.body)
    );
  }

  /** Path part for operation `locationControllerRemoveV1()` */
  static readonly LocationControllerRemoveV1Path = '/api/v1/location/{id}';

  /**
   * Delete a location.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `locationControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  locationControllerRemoveV1$Response(params: LocationControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Location>> {
    return locationControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a location.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `locationControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  locationControllerRemoveV1(params: LocationControllerRemoveV1$Params, context?: HttpContext): Observable<Location> {
    return this.locationControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Location>): Location => r.body)
    );
  }

  /** Path part for operation `locationControllerUpdateV1()` */
  static readonly LocationControllerUpdateV1Path = '/api/v1/location/{id}';

  /**
   * Update a location.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `locationControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  locationControllerUpdateV1$Response(params: LocationControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Location>> {
    return locationControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a location.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `locationControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  locationControllerUpdateV1(params: LocationControllerUpdateV1$Params, context?: HttpContext): Observable<Location> {
    return this.locationControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Location>): Location => r.body)
    );
  }

}
