/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GetMovementResponse } from '../models/get-movement-response';
import { Movement } from '../models/movement';
import { movementControllerCreateV1 } from '../fn/movement/movement-controller-create-v-1';
import { MovementControllerCreateV1$Params } from '../fn/movement/movement-controller-create-v-1';
import { movementControllerFindByDestinationV1 } from '../fn/movement/movement-controller-find-by-destination-v-1';
import { MovementControllerFindByDestinationV1$Params } from '../fn/movement/movement-controller-find-by-destination-v-1';
import { movementControllerFindByOriginV1 } from '../fn/movement/movement-controller-find-by-origin-v-1';
import { MovementControllerFindByOriginV1$Params } from '../fn/movement/movement-controller-find-by-origin-v-1';
import { movementControllerFindByProductV1 } from '../fn/movement/movement-controller-find-by-product-v-1';
import { MovementControllerFindByProductV1$Params } from '../fn/movement/movement-controller-find-by-product-v-1';
import { movementControllerFindOneV1 } from '../fn/movement/movement-controller-find-one-v-1';
import { MovementControllerFindOneV1$Params } from '../fn/movement/movement-controller-find-one-v-1';
import { movementControllerGetAllMovementsV1 } from '../fn/movement/movement-controller-get-all-movements-v-1';
import { MovementControllerGetAllMovementsV1$Params } from '../fn/movement/movement-controller-get-all-movements-v-1';
import { movementControllerRemoveV1 } from '../fn/movement/movement-controller-remove-v-1';
import { MovementControllerRemoveV1$Params } from '../fn/movement/movement-controller-remove-v-1';
import { movementControllerUpdateV1 } from '../fn/movement/movement-controller-update-v-1';
import { MovementControllerUpdateV1$Params } from '../fn/movement/movement-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class MovementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `movementControllerGetAllMovementsV1()` */
  static readonly MovementControllerGetAllMovementsV1Path = '/api/v1/movement';

  /**
   * Get all movements with pagination and filtering.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `movementControllerGetAllMovementsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerGetAllMovementsV1$Response(params?: MovementControllerGetAllMovementsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetMovementResponse>>> {
    return movementControllerGetAllMovementsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all movements with pagination and filtering.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `movementControllerGetAllMovementsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerGetAllMovementsV1(params?: MovementControllerGetAllMovementsV1$Params, context?: HttpContext): Observable<Array<GetMovementResponse>> {
    return this.movementControllerGetAllMovementsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetMovementResponse>>): Array<GetMovementResponse> => r.body)
    );
  }

  /** Path part for operation `movementControllerCreateV1()` */
  static readonly MovementControllerCreateV1Path = '/api/v1/movement';

  /**
   * Create a new movement journal entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `movementControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  movementControllerCreateV1$Response(params: MovementControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Movement>> {
    return movementControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new movement journal entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `movementControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  movementControllerCreateV1(params: MovementControllerCreateV1$Params, context?: HttpContext): Observable<Movement> {
    return this.movementControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Movement>): Movement => r.body)
    );
  }

  /** Path part for operation `movementControllerFindByProductV1()` */
  static readonly MovementControllerFindByProductV1Path = '/api/v1/movement/product/{productId}';

  /**
   * Get all movements for a specific product.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `movementControllerFindByProductV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerFindByProductV1$Response(params: MovementControllerFindByProductV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetMovementResponse>>> {
    return movementControllerFindByProductV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all movements for a specific product.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `movementControllerFindByProductV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerFindByProductV1(params: MovementControllerFindByProductV1$Params, context?: HttpContext): Observable<Array<GetMovementResponse>> {
    return this.movementControllerFindByProductV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetMovementResponse>>): Array<GetMovementResponse> => r.body)
    );
  }

  /** Path part for operation `movementControllerFindByOriginV1()` */
  static readonly MovementControllerFindByOriginV1Path = '/api/v1/movement/origin/{originKind}/{originRefId}';

  /**
   * Get all movements from a specific origin.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `movementControllerFindByOriginV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerFindByOriginV1$Response(params: MovementControllerFindByOriginV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetMovementResponse>>> {
    return movementControllerFindByOriginV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all movements from a specific origin.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `movementControllerFindByOriginV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerFindByOriginV1(params: MovementControllerFindByOriginV1$Params, context?: HttpContext): Observable<Array<GetMovementResponse>> {
    return this.movementControllerFindByOriginV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetMovementResponse>>): Array<GetMovementResponse> => r.body)
    );
  }

  /** Path part for operation `movementControllerFindByDestinationV1()` */
  static readonly MovementControllerFindByDestinationV1Path = '/api/v1/movement/destination/{destKind}/{destRefId}';

  /**
   * Get all movements to a specific destination.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `movementControllerFindByDestinationV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerFindByDestinationV1$Response(params: MovementControllerFindByDestinationV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetMovementResponse>>> {
    return movementControllerFindByDestinationV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all movements to a specific destination.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `movementControllerFindByDestinationV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerFindByDestinationV1(params: MovementControllerFindByDestinationV1$Params, context?: HttpContext): Observable<Array<GetMovementResponse>> {
    return this.movementControllerFindByDestinationV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetMovementResponse>>): Array<GetMovementResponse> => r.body)
    );
  }

  /** Path part for operation `movementControllerFindOneV1()` */
  static readonly MovementControllerFindOneV1Path = '/api/v1/movement/{id}';

  /**
   * Get a movement by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `movementControllerFindOneV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerFindOneV1$Response(params: MovementControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetMovementResponse>> {
    return movementControllerFindOneV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a movement by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `movementControllerFindOneV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerFindOneV1(params: MovementControllerFindOneV1$Params, context?: HttpContext): Observable<GetMovementResponse> {
    return this.movementControllerFindOneV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetMovementResponse>): GetMovementResponse => r.body)
    );
  }

  /** Path part for operation `movementControllerRemoveV1()` */
  static readonly MovementControllerRemoveV1Path = '/api/v1/movement/{id}';

  /**
   * Delete a movement.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `movementControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerRemoveV1$Response(params: MovementControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return movementControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a movement.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `movementControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  movementControllerRemoveV1(params: MovementControllerRemoveV1$Params, context?: HttpContext): Observable<void> {
    return this.movementControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `movementControllerUpdateV1()` */
  static readonly MovementControllerUpdateV1Path = '/api/v1/movement/{id}';

  /**
   * Update a movement.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `movementControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  movementControllerUpdateV1$Response(params: MovementControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Movement>> {
    return movementControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a movement.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `movementControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  movementControllerUpdateV1(params: MovementControllerUpdateV1$Params, context?: HttpContext): Observable<Movement> {
    return this.movementControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Movement>): Movement => r.body)
    );
  }

}
