/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { appControllerGetOverviewStatisticsV1 } from '../fn/overview/app-controller-get-overview-statistics-v-1';
import { AppControllerGetOverviewStatisticsV1$Params } from '../fn/overview/app-controller-get-overview-statistics-v-1';
import { OverviewStatisticsDto } from '../models/overview-statistics-dto';

@Injectable({ providedIn: 'root' })
export class OverviewService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `appControllerGetOverviewStatisticsV1()` */
  static readonly AppControllerGetOverviewStatisticsV1Path = '/api/v1/overview/statistics';

  /**
   * Get platform overview statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appControllerGetOverviewStatisticsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetOverviewStatisticsV1$Response(params?: AppControllerGetOverviewStatisticsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<OverviewStatisticsDto>> {
    return appControllerGetOverviewStatisticsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get platform overview statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appControllerGetOverviewStatisticsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetOverviewStatisticsV1(params?: AppControllerGetOverviewStatisticsV1$Params, context?: HttpContext): Observable<OverviewStatisticsDto> {
    return this.appControllerGetOverviewStatisticsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<OverviewStatisticsDto>): OverviewStatisticsDto => r.body)
    );
  }

}
