/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Podium } from '../models/podium';
import { podiumControllerCreateV1 } from '../fn/podium/podium-controller-create-v-1';
import { PodiumControllerCreateV1$Params } from '../fn/podium/podium-controller-create-v-1';
import { podiumControllerGetAllPodiumsV1 } from '../fn/podium/podium-controller-get-all-podiums-v-1';
import { PodiumControllerGetAllPodiumsV1$Params } from '../fn/podium/podium-controller-get-all-podiums-v-1';
import { podiumControllerRemoveV1 } from '../fn/podium/podium-controller-remove-v-1';
import { PodiumControllerRemoveV1$Params } from '../fn/podium/podium-controller-remove-v-1';
import { podiumControllerUpdateV1 } from '../fn/podium/podium-controller-update-v-1';
import { PodiumControllerUpdateV1$Params } from '../fn/podium/podium-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class PodiumService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `podiumControllerGetAllPodiumsV1()` */
  static readonly PodiumControllerGetAllPodiumsV1Path = '/api/v1/podium';

  /**
   * Get all podiums.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `podiumControllerGetAllPodiumsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  podiumControllerGetAllPodiumsV1$Response(params?: PodiumControllerGetAllPodiumsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Podium>>> {
    return podiumControllerGetAllPodiumsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all podiums.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `podiumControllerGetAllPodiumsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  podiumControllerGetAllPodiumsV1(params?: PodiumControllerGetAllPodiumsV1$Params, context?: HttpContext): Observable<Array<Podium>> {
    return this.podiumControllerGetAllPodiumsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Podium>>): Array<Podium> => r.body)
    );
  }

  /** Path part for operation `podiumControllerCreateV1()` */
  static readonly PodiumControllerCreateV1Path = '/api/v1/podium';

  /**
   * Create a new podium.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `podiumControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  podiumControllerCreateV1$Response(params: PodiumControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Podium>> {
    return podiumControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new podium.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `podiumControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  podiumControllerCreateV1(params: PodiumControllerCreateV1$Params, context?: HttpContext): Observable<Podium> {
    return this.podiumControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Podium>): Podium => r.body)
    );
  }

  /** Path part for operation `podiumControllerRemoveV1()` */
  static readonly PodiumControllerRemoveV1Path = '/api/v1/podium/{id}';

  /**
   * Delete a podium.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `podiumControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  podiumControllerRemoveV1$Response(params: PodiumControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Podium>> {
    return podiumControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a podium.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `podiumControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  podiumControllerRemoveV1(params: PodiumControllerRemoveV1$Params, context?: HttpContext): Observable<Podium> {
    return this.podiumControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Podium>): Podium => r.body)
    );
  }

  /** Path part for operation `podiumControllerUpdateV1()` */
  static readonly PodiumControllerUpdateV1Path = '/api/v1/podium/{id}';

  /**
   * Update a podium.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `podiumControllerUpdateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  podiumControllerUpdateV1$Response(params: PodiumControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Podium>> {
    return podiumControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a podium.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `podiumControllerUpdateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  podiumControllerUpdateV1(params: PodiumControllerUpdateV1$Params, context?: HttpContext): Observable<Podium> {
    return this.podiumControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Podium>): Podium => r.body)
    );
  }

}
