/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Product } from '../models/product';
import { productControllerCreateV1 } from '../fn/product/product-controller-create-v-1';
import { ProductControllerCreateV1$Params } from '../fn/product/product-controller-create-v-1';
import { productControllerGetAllProductsV1 } from '../fn/product/product-controller-get-all-products-v-1';
import { ProductControllerGetAllProductsV1$Params } from '../fn/product/product-controller-get-all-products-v-1';
import { productControllerRemoveV1 } from '../fn/product/product-controller-remove-v-1';
import { ProductControllerRemoveV1$Params } from '../fn/product/product-controller-remove-v-1';
import { productControllerUpdateV1 } from '../fn/product/product-controller-update-v-1';
import { ProductControllerUpdateV1$Params } from '../fn/product/product-controller-update-v-1';
import { ProductResponse } from '../models/product-response';

@Injectable({ providedIn: 'root' })
export class ProductService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `productControllerGetAllProductsV1()` */
  static readonly ProductControllerGetAllProductsV1Path = '/api/v1/product';

  /**
   * Get all products.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `productControllerGetAllProductsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  productControllerGetAllProductsV1$Response(params?: ProductControllerGetAllProductsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
    return productControllerGetAllProductsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all products.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `productControllerGetAllProductsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  productControllerGetAllProductsV1(params?: ProductControllerGetAllProductsV1$Params, context?: HttpContext): Observable<Array<ProductResponse>> {
    return this.productControllerGetAllProductsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponse>>): Array<ProductResponse> => r.body)
    );
  }

  /** Path part for operation `productControllerCreateV1()` */
  static readonly ProductControllerCreateV1Path = '/api/v1/product';

  /**
   * Create a new product.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `productControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  productControllerCreateV1$Response(params: ProductControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponse>> {
    return productControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new product.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `productControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  productControllerCreateV1(params: ProductControllerCreateV1$Params, context?: HttpContext): Observable<ProductResponse> {
    return this.productControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponse>): ProductResponse => r.body)
    );
  }

  /** Path part for operation `productControllerRemoveV1()` */
  static readonly ProductControllerRemoveV1Path = '/api/v1/product/{id}';

  /**
   * Delete a product.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `productControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  productControllerRemoveV1$Response(params: ProductControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    return productControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a product.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `productControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  productControllerRemoveV1(params: ProductControllerRemoveV1$Params, context?: HttpContext): Observable<Product> {
    return this.productControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

  /** Path part for operation `productControllerUpdateV1()` */
  static readonly ProductControllerUpdateV1Path = '/api/v1/product/{id}';

  /**
   * Update a product.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `productControllerUpdateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  productControllerUpdateV1$Response(params: ProductControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Product>> {
    return productControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a product.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `productControllerUpdateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  productControllerUpdateV1(params: ProductControllerUpdateV1$Params, context?: HttpContext): Observable<Product> {
    return this.productControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Product>): Product => r.body)
    );
  }

}
