/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GetProductCategoryResponse } from '../models/get-product-category-response';
import { ProductCategory } from '../models/product-category';
import { productCategoryControllerCreateV1 } from '../fn/product-category/product-category-controller-create-v-1';
import { ProductCategoryControllerCreateV1$Params } from '../fn/product-category/product-category-controller-create-v-1';
import { productCategoryControllerGetAllProductCategoriesV1 } from '../fn/product-category/product-category-controller-get-all-product-categories-v-1';
import { ProductCategoryControllerGetAllProductCategoriesV1$Params } from '../fn/product-category/product-category-controller-get-all-product-categories-v-1';
import { productCategoryControllerRemoveV1 } from '../fn/product-category/product-category-controller-remove-v-1';
import { ProductCategoryControllerRemoveV1$Params } from '../fn/product-category/product-category-controller-remove-v-1';
import { productCategoryControllerUpdateV1 } from '../fn/product-category/product-category-controller-update-v-1';
import { ProductCategoryControllerUpdateV1$Params } from '../fn/product-category/product-category-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class ProductCategoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `productCategoryControllerGetAllProductCategoriesV1()` */
  static readonly ProductCategoryControllerGetAllProductCategoriesV1Path = '/api/v1/product-category';

  /**
   * Get all product categories.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `productCategoryControllerGetAllProductCategoriesV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  productCategoryControllerGetAllProductCategoriesV1$Response(params?: ProductCategoryControllerGetAllProductCategoriesV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetProductCategoryResponse>>> {
    return productCategoryControllerGetAllProductCategoriesV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all product categories.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `productCategoryControllerGetAllProductCategoriesV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  productCategoryControllerGetAllProductCategoriesV1(params?: ProductCategoryControllerGetAllProductCategoriesV1$Params, context?: HttpContext): Observable<Array<GetProductCategoryResponse>> {
    return this.productCategoryControllerGetAllProductCategoriesV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetProductCategoryResponse>>): Array<GetProductCategoryResponse> => r.body)
    );
  }

  /** Path part for operation `productCategoryControllerCreateV1()` */
  static readonly ProductCategoryControllerCreateV1Path = '/api/v1/product-category';

  /**
   * Create a new product category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `productCategoryControllerCreateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  productCategoryControllerCreateV1$Response(params: ProductCategoryControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductCategory>> {
    return productCategoryControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new product category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `productCategoryControllerCreateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  productCategoryControllerCreateV1(params: ProductCategoryControllerCreateV1$Params, context?: HttpContext): Observable<ProductCategory> {
    return this.productCategoryControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductCategory>): ProductCategory => r.body)
    );
  }

  /** Path part for operation `productCategoryControllerRemoveV1()` */
  static readonly ProductCategoryControllerRemoveV1Path = '/api/v1/product-category/{id}';

  /**
   * Delete a product category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `productCategoryControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  productCategoryControllerRemoveV1$Response(params: ProductCategoryControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductCategory>> {
    return productCategoryControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a product category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `productCategoryControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  productCategoryControllerRemoveV1(params: ProductCategoryControllerRemoveV1$Params, context?: HttpContext): Observable<ProductCategory> {
    return this.productCategoryControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductCategory>): ProductCategory => r.body)
    );
  }

  /** Path part for operation `productCategoryControllerUpdateV1()` */
  static readonly ProductCategoryControllerUpdateV1Path = '/api/v1/product-category/{id}';

  /**
   * Update a product category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `productCategoryControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  productCategoryControllerUpdateV1$Response(params: ProductCategoryControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductCategory>> {
    return productCategoryControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a product category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `productCategoryControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  productCategoryControllerUpdateV1(params: ProductCategoryControllerUpdateV1$Params, context?: HttpContext): Observable<ProductCategory> {
    return this.productCategoryControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductCategory>): ProductCategory => r.body)
    );
  }

}
