/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GetProviderResponse } from '../models/get-provider-response';
import { Provider } from '../models/provider';
import { providerControllerCreateV1 } from '../fn/provider/provider-controller-create-v-1';
import { ProviderControllerCreateV1$Params } from '../fn/provider/provider-controller-create-v-1';
import { providerControllerGetAllProvidersV1 } from '../fn/provider/provider-controller-get-all-providers-v-1';
import { ProviderControllerGetAllProvidersV1$Params } from '../fn/provider/provider-controller-get-all-providers-v-1';
import { providerControllerRemoveV1 } from '../fn/provider/provider-controller-remove-v-1';
import { ProviderControllerRemoveV1$Params } from '../fn/provider/provider-controller-remove-v-1';
import { providerControllerUpdateV1 } from '../fn/provider/provider-controller-update-v-1';
import { ProviderControllerUpdateV1$Params } from '../fn/provider/provider-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class ProviderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `providerControllerGetAllProvidersV1()` */
  static readonly ProviderControllerGetAllProvidersV1Path = '/api/v1/provider';

  /**
   * Get all providers.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `providerControllerGetAllProvidersV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  providerControllerGetAllProvidersV1$Response(params?: ProviderControllerGetAllProvidersV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetProviderResponse>>> {
    return providerControllerGetAllProvidersV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all providers.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `providerControllerGetAllProvidersV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  providerControllerGetAllProvidersV1(params?: ProviderControllerGetAllProvidersV1$Params, context?: HttpContext): Observable<Array<GetProviderResponse>> {
    return this.providerControllerGetAllProvidersV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetProviderResponse>>): Array<GetProviderResponse> => r.body)
    );
  }

  /** Path part for operation `providerControllerCreateV1()` */
  static readonly ProviderControllerCreateV1Path = '/api/v1/provider';

  /**
   * Create a new provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `providerControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  providerControllerCreateV1$Response(params: ProviderControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Provider>> {
    return providerControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `providerControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  providerControllerCreateV1(params: ProviderControllerCreateV1$Params, context?: HttpContext): Observable<Provider> {
    return this.providerControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Provider>): Provider => r.body)
    );
  }

  /** Path part for operation `providerControllerRemoveV1()` */
  static readonly ProviderControllerRemoveV1Path = '/api/v1/provider/{id}';

  /**
   * Delete a provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `providerControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  providerControllerRemoveV1$Response(params: ProviderControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Provider>> {
    return providerControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `providerControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  providerControllerRemoveV1(params: ProviderControllerRemoveV1$Params, context?: HttpContext): Observable<Provider> {
    return this.providerControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Provider>): Provider => r.body)
    );
  }

  /** Path part for operation `providerControllerUpdateV1()` */
  static readonly ProviderControllerUpdateV1Path = '/api/v1/provider/{id}';

  /**
   * Update a provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `providerControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  providerControllerUpdateV1$Response(params: ProviderControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Provider>> {
    return providerControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `providerControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  providerControllerUpdateV1(params: ProviderControllerUpdateV1$Params, context?: HttpContext): Observable<Provider> {
    return this.providerControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Provider>): Provider => r.body)
    );
  }

}
