/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { roleControllerCreateUserRoleV1 } from '../fn/role/role-controller-create-user-role-v-1';
import { RoleControllerCreateUserRoleV1$Params } from '../fn/role/role-controller-create-user-role-v-1';
import { roleControllerGetAllRolesV1 } from '../fn/role/role-controller-get-all-roles-v-1';
import { RoleControllerGetAllRolesV1$Params } from '../fn/role/role-controller-get-all-roles-v-1';
import { roleControllerRemoveRoleV1 } from '../fn/role/role-controller-remove-role-v-1';
import { RoleControllerRemoveRoleV1$Params } from '../fn/role/role-controller-remove-role-v-1';
import { roleControllerUpdateRoleV1 } from '../fn/role/role-controller-update-role-v-1';
import { RoleControllerUpdateRoleV1$Params } from '../fn/role/role-controller-update-role-v-1';
import { UserRoleEntity } from '../models/user-role-entity';

@Injectable({ providedIn: 'root' })
export class RoleService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `roleControllerGetAllRolesV1()` */
  static readonly RoleControllerGetAllRolesV1Path = '/api/v1/role';

  /**
   * Get all roles.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roleControllerGetAllRolesV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  roleControllerGetAllRolesV1$Response(params: RoleControllerGetAllRolesV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
    return roleControllerGetAllRolesV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all roles.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roleControllerGetAllRolesV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  roleControllerGetAllRolesV1(params: RoleControllerGetAllRolesV1$Params, context?: HttpContext): Observable<UserRoleEntity> {
    return this.roleControllerGetAllRolesV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserRoleEntity>): UserRoleEntity => r.body)
    );
  }

  /** Path part for operation `roleControllerCreateUserRoleV1()` */
  static readonly RoleControllerCreateUserRoleV1Path = '/api/v1/role';

  /**
   * Create a user role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roleControllerCreateUserRoleV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  roleControllerCreateUserRoleV1$Response(params: RoleControllerCreateUserRoleV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
    return roleControllerCreateUserRoleV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a user role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roleControllerCreateUserRoleV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  roleControllerCreateUserRoleV1(params: RoleControllerCreateUserRoleV1$Params, context?: HttpContext): Observable<UserRoleEntity> {
    return this.roleControllerCreateUserRoleV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserRoleEntity>): UserRoleEntity => r.body)
    );
  }

  /** Path part for operation `roleControllerUpdateRoleV1()` */
  static readonly RoleControllerUpdateRoleV1Path = '/api/v1/role/{id}';

  /**
   * Update a user role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roleControllerUpdateRoleV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  roleControllerUpdateRoleV1$Response(params: RoleControllerUpdateRoleV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
    return roleControllerUpdateRoleV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a user role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roleControllerUpdateRoleV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  roleControllerUpdateRoleV1(params: RoleControllerUpdateRoleV1$Params, context?: HttpContext): Observable<UserRoleEntity> {
    return this.roleControllerUpdateRoleV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserRoleEntity>): UserRoleEntity => r.body)
    );
  }

  /** Path part for operation `roleControllerRemoveRoleV1()` */
  static readonly RoleControllerRemoveRoleV1Path = '/api/v1/role/{id}';

  /**
   * Delete a user role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roleControllerRemoveRoleV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  roleControllerRemoveRoleV1$Response(params: RoleControllerRemoveRoleV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return roleControllerRemoveRoleV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a user role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roleControllerRemoveRoleV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  roleControllerRemoveRoleV1(params: RoleControllerRemoveRoleV1$Params, context?: HttpContext): Observable<void> {
    return this.roleControllerRemoveRoleV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
