/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GetStorageCaseResponseDto } from '../models/get-storage-case-response-dto';
import { StorageCase } from '../models/storage-case';
import { storageCaseControllerCreateV1 } from '../fn/storage-case/storage-case-controller-create-v-1';
import { StorageCaseControllerCreateV1$Params } from '../fn/storage-case/storage-case-controller-create-v-1';
import { storageCaseControllerGetAllStorageCasesV1 } from '../fn/storage-case/storage-case-controller-get-all-storage-cases-v-1';
import { StorageCaseControllerGetAllStorageCasesV1$Params } from '../fn/storage-case/storage-case-controller-get-all-storage-cases-v-1';
import { storageCaseControllerRemoveV1 } from '../fn/storage-case/storage-case-controller-remove-v-1';
import { StorageCaseControllerRemoveV1$Params } from '../fn/storage-case/storage-case-controller-remove-v-1';
import { storageCaseControllerUpdateV1 } from '../fn/storage-case/storage-case-controller-update-v-1';
import { StorageCaseControllerUpdateV1$Params } from '../fn/storage-case/storage-case-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class StorageCaseService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `storageCaseControllerGetAllStorageCasesV1()` */
  static readonly StorageCaseControllerGetAllStorageCasesV1Path = '/api/v1/storage-case';

  /**
   * Get all storage cases.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `storageCaseControllerGetAllStorageCasesV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  storageCaseControllerGetAllStorageCasesV1$Response(params?: StorageCaseControllerGetAllStorageCasesV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetStorageCaseResponseDto>>> {
    return storageCaseControllerGetAllStorageCasesV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all storage cases.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `storageCaseControllerGetAllStorageCasesV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  storageCaseControllerGetAllStorageCasesV1(params?: StorageCaseControllerGetAllStorageCasesV1$Params, context?: HttpContext): Observable<Array<GetStorageCaseResponseDto>> {
    return this.storageCaseControllerGetAllStorageCasesV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetStorageCaseResponseDto>>): Array<GetStorageCaseResponseDto> => r.body)
    );
  }

  /** Path part for operation `storageCaseControllerCreateV1()` */
  static readonly StorageCaseControllerCreateV1Path = '/api/v1/storage-case';

  /**
   * Create a new storage case.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `storageCaseControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  storageCaseControllerCreateV1$Response(params: StorageCaseControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageCase>> {
    return storageCaseControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new storage case.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `storageCaseControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  storageCaseControllerCreateV1(params: StorageCaseControllerCreateV1$Params, context?: HttpContext): Observable<StorageCase> {
    return this.storageCaseControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<StorageCase>): StorageCase => r.body)
    );
  }

  /** Path part for operation `storageCaseControllerRemoveV1()` */
  static readonly StorageCaseControllerRemoveV1Path = '/api/v1/storage-case/{id}';

  /**
   * Delete a storage case.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `storageCaseControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  storageCaseControllerRemoveV1$Response(params: StorageCaseControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageCase>> {
    return storageCaseControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a storage case.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `storageCaseControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  storageCaseControllerRemoveV1(params: StorageCaseControllerRemoveV1$Params, context?: HttpContext): Observable<StorageCase> {
    return this.storageCaseControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<StorageCase>): StorageCase => r.body)
    );
  }

  /** Path part for operation `storageCaseControllerUpdateV1()` */
  static readonly StorageCaseControllerUpdateV1Path = '/api/v1/storage-case/{id}';

  /**
   * Update a storage case.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `storageCaseControllerUpdateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  storageCaseControllerUpdateV1$Response(params: StorageCaseControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageCase>> {
    return storageCaseControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a storage case.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `storageCaseControllerUpdateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  storageCaseControllerUpdateV1(params: StorageCaseControllerUpdateV1$Params, context?: HttpContext): Observable<StorageCase> {
    return this.storageCaseControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<StorageCase>): StorageCase => r.body)
    );
  }

}
