/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GetTownResponseDto } from '../models/get-town-response-dto';
import { townControllerCreateV1 } from '../fn/town/town-controller-create-v-1';
import { TownControllerCreateV1$Params } from '../fn/town/town-controller-create-v-1';
import { townControllerFindAllV1 } from '../fn/town/town-controller-find-all-v-1';
import { TownControllerFindAllV1$Params } from '../fn/town/town-controller-find-all-v-1';
import { townControllerUpdateV1 } from '../fn/town/town-controller-update-v-1';
import { TownControllerUpdateV1$Params } from '../fn/town/town-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class TownService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `townControllerFindAllV1()` */
  static readonly TownControllerFindAllV1Path = '/api/v1/town';

  /**
   * Get all towns.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `townControllerFindAllV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  townControllerFindAllV1$Response(params?: TownControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetTownResponseDto>>> {
    return townControllerFindAllV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all towns.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `townControllerFindAllV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  townControllerFindAllV1(params?: TownControllerFindAllV1$Params, context?: HttpContext): Observable<Array<GetTownResponseDto>> {
    return this.townControllerFindAllV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetTownResponseDto>>): Array<GetTownResponseDto> => r.body)
    );
  }

  /** Path part for operation `townControllerCreateV1()` */
  static readonly TownControllerCreateV1Path = '/api/v1/town';

  /**
   * Create a new town.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `townControllerCreateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  townControllerCreateV1$Response(params: TownControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTownResponseDto>> {
    return townControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new town.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `townControllerCreateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  townControllerCreateV1(params: TownControllerCreateV1$Params, context?: HttpContext): Observable<GetTownResponseDto> {
    return this.townControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetTownResponseDto>): GetTownResponseDto => r.body)
    );
  }

  /** Path part for operation `townControllerUpdateV1()` */
  static readonly TownControllerUpdateV1Path = '/api/v1/town/{id}';

  /**
   * Update a town.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `townControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  townControllerUpdateV1$Response(params: TownControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTownResponseDto>> {
    return townControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a town.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `townControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  townControllerUpdateV1(params: TownControllerUpdateV1$Params, context?: HttpContext): Observable<GetTownResponseDto> {
    return this.townControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetTownResponseDto>): GetTownResponseDto => r.body)
    );
  }

}
