/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GetTransportListResponse } from '../models/get-transport-list-response';
import { transportListControllerCreateV1 } from '../fn/transport-list/transport-list-controller-create-v-1';
import { TransportListControllerCreateV1$Params } from '../fn/transport-list/transport-list-controller-create-v-1';
import { transportListControllerFindOneV1 } from '../fn/transport-list/transport-list-controller-find-one-v-1';
import { TransportListControllerFindOneV1$Params } from '../fn/transport-list/transport-list-controller-find-one-v-1';
import { transportListControllerGetAllTransportListsV1 } from '../fn/transport-list/transport-list-controller-get-all-transport-lists-v-1';
import { TransportListControllerGetAllTransportListsV1$Params } from '../fn/transport-list/transport-list-controller-get-all-transport-lists-v-1';
import { transportListControllerRemoveV1 } from '../fn/transport-list/transport-list-controller-remove-v-1';
import { TransportListControllerRemoveV1$Params } from '../fn/transport-list/transport-list-controller-remove-v-1';
import { transportListControllerUpdateV1 } from '../fn/transport-list/transport-list-controller-update-v-1';
import { TransportListControllerUpdateV1$Params } from '../fn/transport-list/transport-list-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class TransportListService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `transportListControllerGetAllTransportListsV1()` */
  static readonly TransportListControllerGetAllTransportListsV1Path = '/api/v1/transport-list';

  /**
   * Get all transport lists with pagination and filtering.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportListControllerGetAllTransportListsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportListControllerGetAllTransportListsV1$Response(params?: TransportListControllerGetAllTransportListsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetTransportListResponse>>> {
    return transportListControllerGetAllTransportListsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all transport lists with pagination and filtering.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportListControllerGetAllTransportListsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportListControllerGetAllTransportListsV1(params?: TransportListControllerGetAllTransportListsV1$Params, context?: HttpContext): Observable<Array<GetTransportListResponse>> {
    return this.transportListControllerGetAllTransportListsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetTransportListResponse>>): Array<GetTransportListResponse> => r.body)
    );
  }

  /** Path part for operation `transportListControllerCreateV1()` */
  static readonly TransportListControllerCreateV1Path = '/api/v1/transport-list';

  /**
   * Create a new transport list (upload PDF file).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportListControllerCreateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  transportListControllerCreateV1$Response(params: TransportListControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTransportListResponse>> {
    return transportListControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new transport list (upload PDF file).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportListControllerCreateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  transportListControllerCreateV1(params: TransportListControllerCreateV1$Params, context?: HttpContext): Observable<GetTransportListResponse> {
    return this.transportListControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetTransportListResponse>): GetTransportListResponse => r.body)
    );
  }

  /** Path part for operation `transportListControllerFindOneV1()` */
  static readonly TransportListControllerFindOneV1Path = '/api/v1/transport-list/{id}';

  /**
   * Get a transport list by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportListControllerFindOneV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportListControllerFindOneV1$Response(params: TransportListControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTransportListResponse>> {
    return transportListControllerFindOneV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a transport list by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportListControllerFindOneV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportListControllerFindOneV1(params: TransportListControllerFindOneV1$Params, context?: HttpContext): Observable<GetTransportListResponse> {
    return this.transportListControllerFindOneV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetTransportListResponse>): GetTransportListResponse => r.body)
    );
  }

  /** Path part for operation `transportListControllerRemoveV1()` */
  static readonly TransportListControllerRemoveV1Path = '/api/v1/transport-list/{id}';

  /**
   * Delete a transport list.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportListControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportListControllerRemoveV1$Response(params: TransportListControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return transportListControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a transport list.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportListControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportListControllerRemoveV1(params: TransportListControllerRemoveV1$Params, context?: HttpContext): Observable<void> {
    return this.transportListControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `transportListControllerUpdateV1()` */
  static readonly TransportListControllerUpdateV1Path = '/api/v1/transport-list/{id}';

  /**
   * Update a transport list (optionally upload new PDF file).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportListControllerUpdateV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  transportListControllerUpdateV1$Response(params: TransportListControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTransportListResponse>> {
    return transportListControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a transport list (optionally upload new PDF file).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportListControllerUpdateV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  transportListControllerUpdateV1(params: TransportListControllerUpdateV1$Params, context?: HttpContext): Observable<GetTransportListResponse> {
    return this.transportListControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetTransportListResponse>): GetTransportListResponse => r.body)
    );
  }

}
