/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { TransportPodium } from '../models/transport-podium';
import { transportPodiumControllerCreateV1 } from '../fn/transport-podium/transport-podium-controller-create-v-1';
import { TransportPodiumControllerCreateV1$Params } from '../fn/transport-podium/transport-podium-controller-create-v-1';
import { transportPodiumControllerFindAllV1 } from '../fn/transport-podium/transport-podium-controller-find-all-v-1';
import { TransportPodiumControllerFindAllV1$Params } from '../fn/transport-podium/transport-podium-controller-find-all-v-1';
import { transportPodiumControllerFindOneV1 } from '../fn/transport-podium/transport-podium-controller-find-one-v-1';
import { TransportPodiumControllerFindOneV1$Params } from '../fn/transport-podium/transport-podium-controller-find-one-v-1';
import { transportPodiumControllerMarkAsReturnedV1 } from '../fn/transport-podium/transport-podium-controller-mark-as-returned-v-1';
import { TransportPodiumControllerMarkAsReturnedV1$Params } from '../fn/transport-podium/transport-podium-controller-mark-as-returned-v-1';
import { transportPodiumControllerRemoveV1 } from '../fn/transport-podium/transport-podium-controller-remove-v-1';
import { TransportPodiumControllerRemoveV1$Params } from '../fn/transport-podium/transport-podium-controller-remove-v-1';
import { transportPodiumControllerUpdateV1 } from '../fn/transport-podium/transport-podium-controller-update-v-1';
import { TransportPodiumControllerUpdateV1$Params } from '../fn/transport-podium/transport-podium-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class TransportPodiumService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `transportPodiumControllerFindAllV1()` */
  static readonly TransportPodiumControllerFindAllV1Path = '/api/v1/transport-podium';

  /**
   * Get all transport podiums, optionally filtered by transport list ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportPodiumControllerFindAllV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportPodiumControllerFindAllV1$Response(params: TransportPodiumControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransportPodium>>> {
    return transportPodiumControllerFindAllV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all transport podiums, optionally filtered by transport list ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportPodiumControllerFindAllV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportPodiumControllerFindAllV1(params: TransportPodiumControllerFindAllV1$Params, context?: HttpContext): Observable<Array<TransportPodium>> {
    return this.transportPodiumControllerFindAllV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransportPodium>>): Array<TransportPodium> => r.body)
    );
  }

  /** Path part for operation `transportPodiumControllerCreateV1()` */
  static readonly TransportPodiumControllerCreateV1Path = '/api/v1/transport-podium';

  /**
   * Create a new transport podium.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportPodiumControllerCreateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transportPodiumControllerCreateV1$Response(params: TransportPodiumControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportPodium>> {
    return transportPodiumControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new transport podium.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportPodiumControllerCreateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transportPodiumControllerCreateV1(params: TransportPodiumControllerCreateV1$Params, context?: HttpContext): Observable<TransportPodium> {
    return this.transportPodiumControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportPodium>): TransportPodium => r.body)
    );
  }

  /** Path part for operation `transportPodiumControllerFindOneV1()` */
  static readonly TransportPodiumControllerFindOneV1Path = '/api/v1/transport-podium/{id}';

  /**
   * Get a transport podium by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportPodiumControllerFindOneV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportPodiumControllerFindOneV1$Response(params: TransportPodiumControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportPodium>> {
    return transportPodiumControllerFindOneV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a transport podium by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportPodiumControllerFindOneV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportPodiumControllerFindOneV1(params: TransportPodiumControllerFindOneV1$Params, context?: HttpContext): Observable<TransportPodium> {
    return this.transportPodiumControllerFindOneV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportPodium>): TransportPodium => r.body)
    );
  }

  /** Path part for operation `transportPodiumControllerRemoveV1()` */
  static readonly TransportPodiumControllerRemoveV1Path = '/api/v1/transport-podium/{id}';

  /**
   * Remove a transport podium (marks as returned and sets podium state to Available).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportPodiumControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportPodiumControllerRemoveV1$Response(params: TransportPodiumControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return transportPodiumControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Remove a transport podium (marks as returned and sets podium state to Available).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportPodiumControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportPodiumControllerRemoveV1(params: TransportPodiumControllerRemoveV1$Params, context?: HttpContext): Observable<void> {
    return this.transportPodiumControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `transportPodiumControllerUpdateV1()` */
  static readonly TransportPodiumControllerUpdateV1Path = '/api/v1/transport-podium/{id}';

  /**
   * Update a transport podium.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportPodiumControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transportPodiumControllerUpdateV1$Response(params: TransportPodiumControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportPodium>> {
    return transportPodiumControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a transport podium.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportPodiumControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transportPodiumControllerUpdateV1(params: TransportPodiumControllerUpdateV1$Params, context?: HttpContext): Observable<TransportPodium> {
    return this.transportPodiumControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportPodium>): TransportPodium => r.body)
    );
  }

  /** Path part for operation `transportPodiumControllerMarkAsReturnedV1()` */
  static readonly TransportPodiumControllerMarkAsReturnedV1Path = '/api/v1/transport-podium/{id}/return';

  /**
   * Mark transport podium as returned.
   *
   * Records the return of a podium from an event. Updates podium state to Available and marks the transport podium as returned.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportPodiumControllerMarkAsReturnedV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportPodiumControllerMarkAsReturnedV1$Response(params: TransportPodiumControllerMarkAsReturnedV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportPodium>> {
    return transportPodiumControllerMarkAsReturnedV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark transport podium as returned.
   *
   * Records the return of a podium from an event. Updates podium state to Available and marks the transport podium as returned.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportPodiumControllerMarkAsReturnedV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportPodiumControllerMarkAsReturnedV1(params: TransportPodiumControllerMarkAsReturnedV1$Params, context?: HttpContext): Observable<TransportPodium> {
    return this.transportPodiumControllerMarkAsReturnedV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportPodium>): TransportPodium => r.body)
    );
  }

}
