/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { TransportItem } from '../models/transport-item';
import { transportItemControllerCreateV1 } from '../fn/transport-item/transport-item-controller-create-v-1';
import { TransportItemControllerCreateV1$Params } from '../fn/transport-item/transport-item-controller-create-v-1';
import { transportItemControllerFindAllV1 } from '../fn/transport-item/transport-item-controller-find-all-v-1';
import { TransportItemControllerFindAllV1$Params } from '../fn/transport-item/transport-item-controller-find-all-v-1';
import { transportItemControllerFindOneV1 } from '../fn/transport-item/transport-item-controller-find-one-v-1';
import { TransportItemControllerFindOneV1$Params } from '../fn/transport-item/transport-item-controller-find-one-v-1';
import { transportItemControllerMarkAsReturnedV1 } from '../fn/transport-item/transport-item-controller-mark-as-returned-v-1';
import { TransportItemControllerMarkAsReturnedV1$Params } from '../fn/transport-item/transport-item-controller-mark-as-returned-v-1';
import { transportItemControllerUpdateV1 } from '../fn/transport-item/transport-item-controller-update-v-1';
import { TransportItemControllerUpdateV1$Params } from '../fn/transport-item/transport-item-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class TransportItemService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `transportItemControllerFindAllV1()` */
  static readonly TransportItemControllerFindAllV1Path = '/api/v1/transport-item';

  /**
   * Get all transport items, optionally filtered by transport list ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportItemControllerFindAllV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportItemControllerFindAllV1$Response(params: TransportItemControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransportItem>>> {
    return transportItemControllerFindAllV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all transport items, optionally filtered by transport list ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportItemControllerFindAllV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportItemControllerFindAllV1(params: TransportItemControllerFindAllV1$Params, context?: HttpContext): Observable<Array<TransportItem>> {
    return this.transportItemControllerFindAllV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransportItem>>): Array<TransportItem> => r.body)
    );
  }

  /** Path part for operation `transportItemControllerCreateV1()` */
  static readonly TransportItemControllerCreateV1Path = '/api/v1/transport-item';

  /**
   * Create a new transport item.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportItemControllerCreateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transportItemControllerCreateV1$Response(params: TransportItemControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportItem>> {
    return transportItemControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new transport item.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportItemControllerCreateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transportItemControllerCreateV1(params: TransportItemControllerCreateV1$Params, context?: HttpContext): Observable<TransportItem> {
    return this.transportItemControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportItem>): TransportItem => r.body)
    );
  }

  /** Path part for operation `transportItemControllerFindOneV1()` */
  static readonly TransportItemControllerFindOneV1Path = '/api/v1/transport-item/{id}';

  /**
   * Get a transport item by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportItemControllerFindOneV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportItemControllerFindOneV1$Response(params: TransportItemControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportItem>> {
    return transportItemControllerFindOneV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a transport item by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportItemControllerFindOneV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportItemControllerFindOneV1(params: TransportItemControllerFindOneV1$Params, context?: HttpContext): Observable<TransportItem> {
    return this.transportItemControllerFindOneV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportItem>): TransportItem => r.body)
    );
  }

  /** Path part for operation `transportItemControllerUpdateV1()` */
  static readonly TransportItemControllerUpdateV1Path = '/api/v1/transport-item/{id}';

  /**
   * Update a transport item.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportItemControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transportItemControllerUpdateV1$Response(params: TransportItemControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportItem>> {
    return transportItemControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a transport item.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportItemControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  transportItemControllerUpdateV1(params: TransportItemControllerUpdateV1$Params, context?: HttpContext): Observable<TransportItem> {
    return this.transportItemControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportItem>): TransportItem => r.body)
    );
  }

  /** Path part for operation `transportItemControllerMarkAsReturnedV1()` */
  static readonly TransportItemControllerMarkAsReturnedV1Path = '/api/v1/transport-item/{id}/return';

  /**
   * Mark transport item as returned.
   *
   * Records the return of a product from an event. Creates inbound movement, updates product status to Inspecting, and marks the transport item as returned.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `transportItemControllerMarkAsReturnedV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportItemControllerMarkAsReturnedV1$Response(params: TransportItemControllerMarkAsReturnedV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportItem>> {
    return transportItemControllerMarkAsReturnedV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark transport item as returned.
   *
   * Records the return of a product from an event. Creates inbound movement, updates product status to Inspecting, and marks the transport item as returned.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `transportItemControllerMarkAsReturnedV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  transportItemControllerMarkAsReturnedV1(params: TransportItemControllerMarkAsReturnedV1$Params, context?: HttpContext): Observable<TransportItem> {
    return this.transportItemControllerMarkAsReturnedV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportItem>): TransportItem => r.body)
    );
  }

}
