/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginatedUserResponseDto } from '../models/paginated-user-response-dto';
import { userControllerChangePasswordV1 } from '../fn/users/user-controller-change-password-v-1';
import { UserControllerChangePasswordV1$Params } from '../fn/users/user-controller-change-password-v-1';
import { userControllerCreateStaffV1 } from '../fn/users/user-controller-create-staff-v-1';
import { UserControllerCreateStaffV1$Params } from '../fn/users/user-controller-create-staff-v-1';
import { userControllerDeleteStaffV1 } from '../fn/users/user-controller-delete-staff-v-1';
import { UserControllerDeleteStaffV1$Params } from '../fn/users/user-controller-delete-staff-v-1';
import { userControllerGetAllOperatorsV1 } from '../fn/users/user-controller-get-all-operators-v-1';
import { UserControllerGetAllOperatorsV1$Params } from '../fn/users/user-controller-get-all-operators-v-1';
import { userControllerToggleStaffActivationV1 } from '../fn/users/user-controller-toggle-staff-activation-v-1';
import { UserControllerToggleStaffActivationV1$Params } from '../fn/users/user-controller-toggle-staff-activation-v-1';
import { userControllerUpdateProfileV1 } from '../fn/users/user-controller-update-profile-v-1';
import { UserControllerUpdateProfileV1$Params } from '../fn/users/user-controller-update-profile-v-1';
import { userControllerUpdateStaffV1 } from '../fn/users/user-controller-update-staff-v-1';
import { UserControllerUpdateStaffV1$Params } from '../fn/users/user-controller-update-staff-v-1';
import { UserResponseDto } from '../models/user-response-dto';


/**
 * User management endpoints
 */
@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userControllerGetAllOperatorsV1()` */
  static readonly UserControllerGetAllOperatorsV1Path = '/api/v1/user';

  /**
   * Get all users.
   *
   * Retrieve all user accounts. Admin can access all users (OPERATOR and USER), operator can only access USERs.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerGetAllOperatorsV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetAllOperatorsV1$Response(params?: UserControllerGetAllOperatorsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PaginatedUserResponseDto>>> {
    return userControllerGetAllOperatorsV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all users.
   *
   * Retrieve all user accounts. Admin can access all users (OPERATOR and USER), operator can only access USERs.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerGetAllOperatorsV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetAllOperatorsV1(params?: UserControllerGetAllOperatorsV1$Params, context?: HttpContext): Observable<Array<PaginatedUserResponseDto>> {
    return this.userControllerGetAllOperatorsV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PaginatedUserResponseDto>>): Array<PaginatedUserResponseDto> => r.body)
    );
  }

  /** Path part for operation `userControllerCreateStaffV1()` */
  static readonly UserControllerCreateStaffV1Path = '/api/v1/user/create-staff';

  /**
   * Create staff member.
   *
   * Create a new staff member account. Admin access required. Optionally upload a profile picture.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerCreateStaffV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  userControllerCreateStaffV1$Response(params: UserControllerCreateStaffV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerCreateStaffV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create staff member.
   *
   * Create a new staff member account. Admin access required. Optionally upload a profile picture.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerCreateStaffV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  userControllerCreateStaffV1(params: UserControllerCreateStaffV1$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerCreateStaffV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerUpdateStaffV1()` */
  static readonly UserControllerUpdateStaffV1Path = '/api/v1/user/update-staff/{idUser}';

  /**
   * Update staff member.
   *
   * Update an existing staff member account. Admin access required. Optionally upload a profile picture.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdateStaffV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  userControllerUpdateStaffV1$Response(params: UserControllerUpdateStaffV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerUpdateStaffV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update staff member.
   *
   * Update an existing staff member account. Admin access required. Optionally upload a profile picture.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdateStaffV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  userControllerUpdateStaffV1(params: UserControllerUpdateStaffV1$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerUpdateStaffV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerToggleStaffActivationV1()` */
  static readonly UserControllerToggleStaffActivationV1Path = '/api/v1/user/{id}/toggle-activation';

  /**
   * Toggle staff member activation status.
   *
   * Toggle the activation status of an existing staff member account. Admin access required.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerToggleStaffActivationV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerToggleStaffActivationV1$Response(params: UserControllerToggleStaffActivationV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerToggleStaffActivationV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle staff member activation status.
   *
   * Toggle the activation status of an existing staff member account. Admin access required.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerToggleStaffActivationV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerToggleStaffActivationV1(params: UserControllerToggleStaffActivationV1$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerToggleStaffActivationV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerDeleteStaffV1()` */
  static readonly UserControllerDeleteStaffV1Path = '/api/v1/user/delete-staff/{id}';

  /**
   * Delete staff member.
   *
   * Delete an existing staff member account. Admin access required.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerDeleteStaffV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerDeleteStaffV1$Response(params: UserControllerDeleteStaffV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerDeleteStaffV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete staff member.
   *
   * Delete an existing staff member account. Admin access required.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerDeleteStaffV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerDeleteStaffV1(params: UserControllerDeleteStaffV1$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerDeleteStaffV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerUpdateProfileV1()` */
  static readonly UserControllerUpdateProfileV1Path = '/api/v1/user/update-profile';

  /**
   * Update current user profile.
   *
   * Update the profile of the currently authenticated user. Optionally upload a profile picture.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdateProfileV1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  userControllerUpdateProfileV1$Response(params: UserControllerUpdateProfileV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    return userControllerUpdateProfileV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update current user profile.
   *
   * Update the profile of the currently authenticated user. Optionally upload a profile picture.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdateProfileV1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  userControllerUpdateProfileV1(params: UserControllerUpdateProfileV1$Params, context?: HttpContext): Observable<UserResponseDto> {
    return this.userControllerUpdateProfileV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `userControllerChangePasswordV1()` */
  static readonly UserControllerChangePasswordV1Path = '/api/v1/user/change-password';

  /**
   * Change user password.
   *
   * Change the password of the currently authenticated user. Requires current password for verification.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerChangePasswordV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerChangePasswordV1$Response(params: UserControllerChangePasswordV1$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
'user'?: {
};
}>> {
    return userControllerChangePasswordV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Change user password.
   *
   * Change the password of the currently authenticated user. Requires current password for verification.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerChangePasswordV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerChangePasswordV1(params: UserControllerChangePasswordV1$Params, context?: HttpContext): Observable<{
'message'?: string;
'user'?: {
};
}> {
    return this.userControllerChangePasswordV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'message'?: string;
'user'?: {
};
}>): {
'message'?: string;
'user'?: {
};
} => r.body)
    );
  }

}
