/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GetWarehouseResponse } from '../models/get-warehouse-response';
import { warehouseControllerCreateV1 } from '../fn/warehouse/warehouse-controller-create-v-1';
import { WarehouseControllerCreateV1$Params } from '../fn/warehouse/warehouse-controller-create-v-1';
import { warehouseControllerFindAllV1 } from '../fn/warehouse/warehouse-controller-find-all-v-1';
import { WarehouseControllerFindAllV1$Params } from '../fn/warehouse/warehouse-controller-find-all-v-1';
import { warehouseControllerRemoveV1 } from '../fn/warehouse/warehouse-controller-remove-v-1';
import { WarehouseControllerRemoveV1$Params } from '../fn/warehouse/warehouse-controller-remove-v-1';
import { warehouseControllerUpdateV1 } from '../fn/warehouse/warehouse-controller-update-v-1';
import { WarehouseControllerUpdateV1$Params } from '../fn/warehouse/warehouse-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class WarehouseService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `warehouseControllerFindAllV1()` */
  static readonly WarehouseControllerFindAllV1Path = '/api/v1/warehouse';

  /**
   * Get all warehouses.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warehouseControllerFindAllV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  warehouseControllerFindAllV1$Response(params?: WarehouseControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetWarehouseResponse>>> {
    return warehouseControllerFindAllV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all warehouses.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warehouseControllerFindAllV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  warehouseControllerFindAllV1(params?: WarehouseControllerFindAllV1$Params, context?: HttpContext): Observable<Array<GetWarehouseResponse>> {
    return this.warehouseControllerFindAllV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetWarehouseResponse>>): Array<GetWarehouseResponse> => r.body)
    );
  }

  /** Path part for operation `warehouseControllerCreateV1()` */
  static readonly WarehouseControllerCreateV1Path = '/api/v1/warehouse';

  /**
   * Create a new warehouse.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warehouseControllerCreateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  warehouseControllerCreateV1$Response(params: WarehouseControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetWarehouseResponse>> {
    return warehouseControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new warehouse.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warehouseControllerCreateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  warehouseControllerCreateV1(params: WarehouseControllerCreateV1$Params, context?: HttpContext): Observable<GetWarehouseResponse> {
    return this.warehouseControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetWarehouseResponse>): GetWarehouseResponse => r.body)
    );
  }

  /** Path part for operation `warehouseControllerRemoveV1()` */
  static readonly WarehouseControllerRemoveV1Path = '/api/v1/warehouse/{id}';

  /**
   * Delete a warehouse.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warehouseControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  warehouseControllerRemoveV1$Response(params: WarehouseControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return warehouseControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a warehouse.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warehouseControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  warehouseControllerRemoveV1(params: WarehouseControllerRemoveV1$Params, context?: HttpContext): Observable<void> {
    return this.warehouseControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `warehouseControllerUpdateV1()` */
  static readonly WarehouseControllerUpdateV1Path = '/api/v1/warehouse/{id}';

  /**
   * Update a warehouse.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `warehouseControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  warehouseControllerUpdateV1$Response(params: WarehouseControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetWarehouseResponse>> {
    return warehouseControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a warehouse.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `warehouseControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  warehouseControllerUpdateV1(params: WarehouseControllerUpdateV1$Params, context?: HttpContext): Observable<GetWarehouseResponse> {
    return this.warehouseControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<GetWarehouseResponse>): GetWarehouseResponse => r.body)
    );
  }

}
