/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponseDto } from '../../models/user-response-dto';

export interface UserControllerCreateStaffV1$Params {
      body: {
'firstName'?: string;
'lastName'?: string;
'email'?: string;
'phoneNumber'?: string;
'roleCode'?: 'ADMIN' | 'ALPHA_STORE_MANAGER' | 'MARKETER' | 'LOGISTIC_MANAGER';

/**
 * Profile picture image file (JPEG, PNG, WebP)
 */
'profilePicture'?: Blob;
}
}

export function userControllerCreateStaffV1(http: HttpClient, rootUrl: string, params: UserControllerCreateStaffV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
  const rb = new RequestBuilder(rootUrl, userControllerCreateStaffV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponseDto>;
    })
  );
}

userControllerCreateStaffV1.PATH = '/api/v1/user/create-staff';
