/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChangePasswordDto } from '../../models/change-password-dto';

export interface UserControllerChangePasswordV1$Params {
      body: ChangePasswordDto
}

export function userControllerChangePasswordV1(http: HttpClient, rootUrl: string, params: UserControllerChangePasswordV1$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
'user'?: {
};
}>> {
  const rb = new RequestBuilder(rootUrl, userControllerChangePasswordV1.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'message'?: string;
      'user'?: {
      };
      }>;
    })
  );
}

userControllerChangePasswordV1.PATH = '/api/v1/user/change-password';
