/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateStaffMultipartDto } from '../../models/update-staff-multipart-dto';
import { UserResponseDto } from '../../models/user-response-dto';

export interface UserControllerUpdateStaffV1$Params {

/**
 * Staff member ID to update
 */
  idUser: number;
  
    /**
     * Staff member update data with optional profile picture
     */
    body: UpdateStaffMultipartDto
}

export function userControllerUpdateStaffV1(http: HttpClient, rootUrl: string, params: UserControllerUpdateStaffV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
  const rb = new RequestBuilder(rootUrl, userControllerUpdateStaffV1.PATH, 'put');
  if (params) {
    rb.path('idUser', params.idUser, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponseDto>;
    })
  );
}

userControllerUpdateStaffV1.PATH = '/api/v1/user/update-staff/{idUser}';
