/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CountryResponseDto } from '../../models/country-response-dto';
import { CreateCountryDto } from '../../models/create-country-dto';

export interface CountryControllerCreateV1$Params {
      body: CreateCountryDto
}

export function countryControllerCreateV1(http: HttpClient, rootUrl: string, params: CountryControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<CountryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, countryControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CountryResponseDto>;
    })
  );
}

countryControllerCreateV1.PATH = '/api/v1/country';
