/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CountryResponseDto } from '../../models/country-response-dto';

export interface CountryControllerFindAllV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Name of the country
 */
  name?: string;

/**
 * Region of the country
 */
  region?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'long_name:asc' | 'long_name:desc' | 'short_name:asc' | 'short_name:desc' | 'regionOfWorld:asc' | 'regionOfWorld:desc';
}

export function countryControllerFindAllV1(http: HttpClient, rootUrl: string, params?: CountryControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<CountryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, countryControllerFindAllV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('name', params.name, {});
    rb.query('region', params.region, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CountryResponseDto>;
    })
  );
}

countryControllerFindAllV1.PATH = '/api/v1/country';
