/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { OverviewService } from './services/overview.service';
import { UsersService } from './services/users.service';
import { RoleService } from './services/role.service';
import { AuthService } from './services/auth.service';
import { ProductService } from './services/product.service';
import { ProductCategoryService } from './services/product-category.service';
import { LocationService } from './services/location.service';
import { WarehouseService } from './services/warehouse.service';
import { TownService } from './services/town.service';
import { CountryService } from './services/country.service';
import { ProviderService } from './services/provider.service';
import { StorageCaseService } from './services/storage-case.service';
import { RepairService } from './services/repair.service';
import { PodiumService } from './services/podium.service';
import { ConsumableService } from './services/consumable.service';
import { ExpoEventService } from './services/expo-event.service';
import { TransportListService } from './services/transport-list.service';
import { TransportItemService } from './services/transport-item.service';
import { MovementService } from './services/movement.service';
import { InspectionService } from './services/inspection.service';
import { DocumentService } from './services/document.service';
import { TransportPodiumService } from './services/transport-podium.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    OverviewService,
    UsersService,
    RoleService,
    AuthService,
    ProductService,
    ProductCategoryService,
    LocationService,
    WarehouseService,
    TownService,
    CountryService,
    ProviderService,
    StorageCaseService,
    RepairService,
    PodiumService,
    ConsumableService,
    ExpoEventService,
    TransportListService,
    TransportItemService,
    MovementService,
    InspectionService,
    DocumentService,
    TransportPodiumService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
