/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetProductCategoryResponse } from '../../models/get-product-category-response';

export interface ProductCategoryControllerGetAllProductCategoriesV1$Params {

/**
 * Name of the product category
 */
  name?: string;

/**
 * Code of the product category
 */
  code?: string;

/**
 * Description of the product category
 */
  description?: string;

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'name:asc' | 'name:desc' | 'code:asc' | 'code:desc';
}

export function productCategoryControllerGetAllProductCategoriesV1(http: HttpClient, rootUrl: string, params?: ProductCategoryControllerGetAllProductCategoriesV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetProductCategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, productCategoryControllerGetAllProductCategoriesV1.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('code', params.code, {});
    rb.query('description', params.description, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetProductCategoryResponse>>;
    })
  );
}

productCategoryControllerGetAllProductCategoriesV1.PATH = '/api/v1/product-category';
