/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetTownResponseDto } from '../../models/get-town-response-dto';

export interface TownControllerFindAllV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Name of the town
 */
  name?: string;

/**
 * Country id
 */
  countryId?: number;
}

export function townControllerFindAllV1(http: HttpClient, rootUrl: string, params?: TownControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetTownResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, townControllerFindAllV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('name', params.name, {});
    rb.query('countryId', params.countryId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetTownResponseDto>>;
    })
  );
}

townControllerFindAllV1.PATH = '/api/v1/town';
