/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetTownResponseDto } from '../../models/get-town-response-dto';
import { UpdateTownDto } from '../../models/update-town-dto';

export interface TownControllerUpdateV1$Params {
  id: number;
      body: UpdateTownDto
}

export function townControllerUpdateV1(http: HttpClient, rootUrl: string, params: TownControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTownResponseDto>> {
  const rb = new RequestBuilder(rootUrl, townControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetTownResponseDto>;
    })
  );
}

townControllerUpdateV1.PATH = '/api/v1/town/{id}';
