/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTownDto } from '../../models/create-town-dto';
import { GetTownResponseDto } from '../../models/get-town-response-dto';

export interface TownControllerCreateV1$Params {
      body: CreateTownDto
}

export function townControllerCreateV1(http: HttpClient, rootUrl: string, params: TownControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTownResponseDto>> {
  const rb = new RequestBuilder(rootUrl, townControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetTownResponseDto>;
    })
  );
}

townControllerCreateV1.PATH = '/api/v1/town';
