/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePodiumDto } from '../../models/create-podium-dto';
import { Podium } from '../../models/podium';

export interface PodiumControllerCreateV1$Params {
      body: CreatePodiumDto
}

export function podiumControllerCreateV1(http: HttpClient, rootUrl: string, params: PodiumControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Podium>> {
  const rb = new RequestBuilder(rootUrl, podiumControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Podium>;
    })
  );
}

podiumControllerCreateV1.PATH = '/api/v1/podium';
