/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Podium } from '../../models/podium';

export interface PodiumControllerRemoveV1$Params {
  id: number;
}

export function podiumControllerRemoveV1(http: HttpClient, rootUrl: string, params: PodiumControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Podium>> {
  const rb = new RequestBuilder(rootUrl, podiumControllerRemoveV1.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Podium>;
    })
  );
}

podiumControllerRemoveV1.PATH = '/api/v1/podium/{id}';
