/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Podium } from '../../models/podium';

export interface PodiumControllerGetAllPodiumsV1$Params {

/**
 * The ref of the storage case
 */
  ref?: string;

/**
 * The name of the podium
 */
  name?: string;

/**
 * The length of the podium in mm
 */
  lengthMm?: number;

/**
 * The width of the podium in mm
 */
  widthMm?: number;

/**
 * The height of the podium in mm
 */
  heightMm?: number;

/**
 * The state of the podium
 */
  state?: 'AVAILABLE' | 'IN_USE' | 'UNDER_REPAIR';

/**
 * The location id of the podium
 */
  locationId?: number;

/**
 * The observations of the podium
 */
  observations?: string;

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc';
}

export function podiumControllerGetAllPodiumsV1(http: HttpClient, rootUrl: string, params?: PodiumControllerGetAllPodiumsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Podium>>> {
  const rb = new RequestBuilder(rootUrl, podiumControllerGetAllPodiumsV1.PATH, 'get');
  if (params) {
    rb.query('ref', params.ref, {});
    rb.query('name', params.name, {});
    rb.query('lengthMm', params.lengthMm, {});
    rb.query('widthMm', params.widthMm, {});
    rb.query('heightMm', params.heightMm, {});
    rb.query('state', params.state, {});
    rb.query('locationId', params.locationId, {});
    rb.query('observations', params.observations, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Podium>>;
    })
  );
}

podiumControllerGetAllPodiumsV1.PATH = '/api/v1/podium';
