/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetMovementResponse } from '../../models/get-movement-response';

export interface MovementControllerFindByOriginV1$Params {

/**
 * The kind of origin (Warehouse, Event, Provider, Repair)
 */
  originKind: 'Warehouse' | 'Event' | 'Provider' | 'Repair';

/**
 * The reference ID of the origin
 */
  originRefId: number;
}

export function movementControllerFindByOriginV1(http: HttpClient, rootUrl: string, params: MovementControllerFindByOriginV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetMovementResponse>>> {
  const rb = new RequestBuilder(rootUrl, movementControllerFindByOriginV1.PATH, 'get');
  if (params) {
    rb.path('originKind', params.originKind, {});
    rb.path('originRefId', params.originRefId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetMovementResponse>>;
    })
  );
}

movementControllerFindByOriginV1.PATH = '/api/v1/movement/origin/{originKind}/{originRefId}';
