/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMovementDto } from '../../models/create-movement-dto';
import { Movement } from '../../models/movement';

export interface MovementControllerCreateV1$Params {
      body: CreateMovementDto
}

export function movementControllerCreateV1(http: HttpClient, rootUrl: string, params: MovementControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Movement>> {
  const rb = new RequestBuilder(rootUrl, movementControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Movement>;
    })
  );
}

movementControllerCreateV1.PATH = '/api/v1/movement';
