/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetMovementResponse } from '../../models/get-movement-response';

export interface MovementControllerGetAllMovementsV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by product ID
 */
  productId?: number;

/**
 * Filter by movement type
 */
  type?: 'Outbound' | 'Inbound';

/**
 * Filter by origin kind
 */
  originKind?: 'Warehouse' | 'Event' | 'Provider' | 'Repair';

/**
 * Filter by origin reference ID
 */
  originRefId?: number;

/**
 * Filter by destination kind
 */
  destKind?: 'Warehouse' | 'Event' | 'Provider' | 'Repair';

/**
 * Filter by destination reference ID
 */
  destRefId?: number;

/**
 * Filter by start date (movements on or after this date)
 */
  startDate?: string;

/**
 * Filter by end date (movements on or before this date)
 */
  endDate?: string;
}

export function movementControllerGetAllMovementsV1(http: HttpClient, rootUrl: string, params?: MovementControllerGetAllMovementsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetMovementResponse>>> {
  const rb = new RequestBuilder(rootUrl, movementControllerGetAllMovementsV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('productId', params.productId, {});
    rb.query('type', params.type, {});
    rb.query('originKind', params.originKind, {});
    rb.query('originRefId', params.originRefId, {});
    rb.query('destKind', params.destKind, {});
    rb.query('destRefId', params.destRefId, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetMovementResponse>>;
    })
  );
}

movementControllerGetAllMovementsV1.PATH = '/api/v1/movement';
