/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Movement } from '../../models/movement';

export interface MovementControllerFindByDestinationV1$Params {

/**
 * The kind of destination (Warehouse, Event, Provider, Repair)
 */
  destKind: 'Warehouse' | 'Event' | 'Provider' | 'Repair';

/**
 * The reference ID of the destination
 */
  destRefId: number;
}

export function movementControllerFindByDestinationV1(http: HttpClient, rootUrl: string, params: MovementControllerFindByDestinationV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Movement>>> {
  const rb = new RequestBuilder(rootUrl, movementControllerFindByDestinationV1.PATH, 'get');
  if (params) {
    rb.path('destKind', params.destKind, {});
    rb.path('destRefId', params.destRefId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Movement>>;
    })
  );
}

movementControllerFindByDestinationV1.PATH = '/api/v1/movement/destination/{destKind}/{destRefId}';
