/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateUserRoleDto } from '../../models/update-user-role-dto';
import { UserRoleEntity } from '../../models/user-role-entity';

export interface RoleControllerUpdateRoleV1$Params {
  id: number;
      body: UpdateUserRoleDto
}

export function roleControllerUpdateRoleV1(http: HttpClient, rootUrl: string, params: RoleControllerUpdateRoleV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
  const rb = new RequestBuilder(rootUrl, roleControllerUpdateRoleV1.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserRoleEntity>;
    })
  );
}

roleControllerUpdateRoleV1.PATH = '/api/v1/role/{id}';
