/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserRoleEntity } from '../../models/user-role-entity';

export interface RoleControllerGetAllRolesV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Code of the role
 */
  code: string;
}

export function roleControllerGetAllRolesV1(http: HttpClient, rootUrl: string, params: RoleControllerGetAllRolesV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
  const rb = new RequestBuilder(rootUrl, roleControllerGetAllRolesV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserRoleEntity>;
    })
  );
}

roleControllerGetAllRolesV1.PATH = '/api/v1/role';
