/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateUserRoleDto } from '../../models/create-user-role-dto';
import { UserRoleEntity } from '../../models/user-role-entity';

export interface RoleControllerCreateUserRoleV1$Params {
      body: CreateUserRoleDto
}

export function roleControllerCreateUserRoleV1(http: HttpClient, rootUrl: string, params: RoleControllerCreateUserRoleV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRoleEntity>> {
  const rb = new RequestBuilder(rootUrl, roleControllerCreateUserRoleV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserRoleEntity>;
    })
  );
}

roleControllerCreateUserRoleV1.PATH = '/api/v1/role';
