/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Location } from '../../models/location';

export interface LocationControllerGetAllLocationsV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Warehouse ID of the location
 */
  warehouseId?: number;

/**
 * Aisle of the location
 */
  aisle?: string;

/**
 * Level number of the location
 */
  levelNo?: number;

/**
 * Position label of the location
 */
  positionLabel?: string;

/**
 * Notes of the location
 */
  notes?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'aisle:asc' | 'aisle:desc' | 'levelNo:asc' | 'levelNo:desc' | 'positionLabel:asc' | 'positionLabel:desc';
}

export function locationControllerGetAllLocationsV1(http: HttpClient, rootUrl: string, params?: LocationControllerGetAllLocationsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Location>>> {
  const rb = new RequestBuilder(rootUrl, locationControllerGetAllLocationsV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('warehouseId', params.warehouseId, {});
    rb.query('aisle', params.aisle, {});
    rb.query('levelNo', params.levelNo, {});
    rb.query('positionLabel', params.positionLabel, {});
    rb.query('notes', params.notes, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Location>>;
    })
  );
}

locationControllerGetAllLocationsV1.PATH = '/api/v1/location';
