/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Location } from '../../models/location';
import { UpdateLocationDto } from '../../models/update-location-dto';

export interface LocationControllerUpdateV1$Params {
  id: number;
      body: UpdateLocationDto
}

export function locationControllerUpdateV1(http: HttpClient, rootUrl: string, params: LocationControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Location>> {
  const rb = new RequestBuilder(rootUrl, locationControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Location>;
    })
  );
}

locationControllerUpdateV1.PATH = '/api/v1/location/{id}';
