/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateLocationDto } from '../../models/create-location-dto';
import { Location } from '../../models/location';

export interface LocationControllerCreateV1$Params {
      body: CreateLocationDto
}

export function locationControllerCreateV1(http: HttpClient, rootUrl: string, params: LocationControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Location>> {
  const rb = new RequestBuilder(rootUrl, locationControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Location>;
    })
  );
}

locationControllerCreateV1.PATH = '/api/v1/location';
