/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OverviewStatisticsDto } from '../../models/overview-statistics-dto';

export interface AppControllerGetOverviewStatisticsV1$Params {
}

export function appControllerGetOverviewStatisticsV1(http: HttpClient, rootUrl: string, params?: AppControllerGetOverviewStatisticsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<OverviewStatisticsDto>> {
  const rb = new RequestBuilder(rootUrl, appControllerGetOverviewStatisticsV1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OverviewStatisticsDto>;
    })
  );
}

appControllerGetOverviewStatisticsV1.PATH = '/api/v1/overview/statistics';
