/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetTransportListResponse } from '../../models/get-transport-list-response';
import { UpdateTransportListDto } from '../../models/update-transport-list-dto';

export interface TransportListControllerUpdateV1$Params {
  id: number;
      body: UpdateTransportListDto
}

export function transportListControllerUpdateV1(http: HttpClient, rootUrl: string, params: TransportListControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTransportListResponse>> {
  const rb = new RequestBuilder(rootUrl, transportListControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetTransportListResponse>;
    })
  );
}

transportListControllerUpdateV1.PATH = '/api/v1/transport-list/{id}';
