/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTransportListDto } from '../../models/create-transport-list-dto';
import { GetTransportListResponse } from '../../models/get-transport-list-response';

export interface TransportListControllerCreateV1$Params {
      body: CreateTransportListDto
}

export function transportListControllerCreateV1(http: HttpClient, rootUrl: string, params: TransportListControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetTransportListResponse>> {
  const rb = new RequestBuilder(rootUrl, transportListControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetTransportListResponse>;
    })
  );
}

transportListControllerCreateV1.PATH = '/api/v1/transport-list';
