/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetTransportListResponse } from '../../models/get-transport-list-response';

export interface TransportListControllerGetAllTransportListsV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by event ID
 */
  eventId?: number;

/**
 * Filter by transport list status
 */
  status?: 'Active' | 'Archived';

/**
 * Filter by creator user ID
 */
  createdBy?: number;

/**
 * Sort order (field:direction)
 */
  orderBy?: string;
}

export function transportListControllerGetAllTransportListsV1(http: HttpClient, rootUrl: string, params?: TransportListControllerGetAllTransportListsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetTransportListResponse>>> {
  const rb = new RequestBuilder(rootUrl, transportListControllerGetAllTransportListsV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('eventId', params.eventId, {});
    rb.query('status', params.status, {});
    rb.query('createdBy', params.createdBy, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetTransportListResponse>>;
    })
  );
}

transportListControllerGetAllTransportListsV1.PATH = '/api/v1/transport-list';
