/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponse } from '../../models/product-response';

export interface ProductControllerGetAllProductsV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Name of the product
 */
  name?: string;

/**
 * Ref of the product
 */
  ref?: string;

/**
 * Status of the product
 */
  status?: string;

/**
 * Category ID of the product
 */
  categoryId?: number;

/**
 * Location ID of the product
 */
  locationId?: number;

/**
 * Provider ID of the product
 */
  providerId?: number;

/**
 * Description of the product
 */
  description?: string;

/**
 * Entry date of the product
 */
  entryDate?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'deliveryDate:asc' | 'deliveryDate:desc' | 'pricePerKg:asc' | 'pricePerKg:desc';
}

export function productControllerGetAllProductsV1(http: HttpClient, rootUrl: string, params?: ProductControllerGetAllProductsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponse>>> {
  const rb = new RequestBuilder(rootUrl, productControllerGetAllProductsV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('name', params.name, {});
    rb.query('ref', params.ref, {});
    rb.query('status', params.status, {});
    rb.query('categoryId', params.categoryId, {});
    rb.query('locationId', params.locationId, {});
    rb.query('providerId', params.providerId, {});
    rb.query('description', params.description, {});
    rb.query('entryDate', params.entryDate, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductResponse>>;
    })
  );
}

productControllerGetAllProductsV1.PATH = '/api/v1/product';
