/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransportItem } from '../../models/transport-item';
import { UpdateTransportItemDto } from '../../models/update-transport-item-dto';

export interface TransportItemControllerUpdateV1$Params {
  id: number;
      body: UpdateTransportItemDto
}

export function transportItemControllerUpdateV1(http: HttpClient, rootUrl: string, params: TransportItemControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportItem>> {
  const rb = new RequestBuilder(rootUrl, transportItemControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransportItem>;
    })
  );
}

transportItemControllerUpdateV1.PATH = '/api/v1/transport-item/{id}';
