/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransportItem } from '../../models/transport-item';

export interface TransportItemControllerFindAllV1$Params {
  transportListId: number;
}

export function transportItemControllerFindAllV1(http: HttpClient, rootUrl: string, params: TransportItemControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransportItem>>> {
  const rb = new RequestBuilder(rootUrl, transportItemControllerFindAllV1.PATH, 'get');
  if (params) {
    rb.query('transportListId', params.transportListId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TransportItem>>;
    })
  );
}

transportItemControllerFindAllV1.PATH = '/api/v1/transport-item';
