/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransportItem } from '../../models/transport-item';

export interface TransportItemControllerFindOneV1$Params {
  id: number;
}

export function transportItemControllerFindOneV1(http: HttpClient, rootUrl: string, params: TransportItemControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportItem>> {
  const rb = new RequestBuilder(rootUrl, transportItemControllerFindOneV1.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransportItem>;
    })
  );
}

transportItemControllerFindOneV1.PATH = '/api/v1/transport-item/{id}';
