/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityTimeSeries {
  date: string;
  inspections: number;
  movements: number;
  repairs: number;
}
