/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangePasswordDto {

  /**
   * Current password
   */
  currentPassword: string;

  /**
   * New password - must contain at least one uppercase letter, one lowercase letter, one number
   */
  newPassword: string;
}
