/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ConsumableCategory {
  Accessories = 'Accessories',
  Tools = 'Tools',
  Materials = 'Materials',
  Other = 'Other'
}
