/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CountryResponseDto {
  createdAt: string;
  id: number;
  name: string;
  regionOfWorld: string;
  updatedAt: string;
}
