/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CountryResponse {

  /**
   * ID of the country
   */
  id: number;

  /**
   * Name of the country
   */
  name: string;
}
