/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProviderDto {

  /**
   * Provider address
   */
  address?: string;

  /**
   * Contact person name
   */
  contactName?: string;

  /**
   * Contact email address
   */
  email?: string;

  /**
   * The name of the provider
   */
  name: string;

  /**
   * Contact phone number
   */
  phone?: string;

  /**
   * Additional remarks about the provider
   */
  remarks?: string;

  /**
   * The type of provider
   */
  type: 'MANUFACTURER' | 'REPAIRER' | 'CARRIER';
}
