/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTransportListDto {

  /**
   * The ID of the expo event this transport list belongs to
   */
  eventId: number;

  /**
   * Name of the transport list
   */
  name: string;

  /**
   * Warehouse out date (store exit date)
   */
  warehouseOutDate: string;

  /**
   * Warehouse return date
   */
  warehouseReturnDate: string;
}
