/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTransportListDto {

  /**
   * The ID of the expo event this transport list belongs to
   */
  eventId: number;

  /**
   * Name of the transport list
   */
  name: string;

  /**
   * PDF file for the transport list
   */
  pdfFile: Blob;
}
