/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateExpoEventDto {

  /**
   * The end date of the expo event (YYYY-MM-DD)
   */
  endDate: string;

  /**
   * The name of the expo event
   */
  name: string;

  /**
   * Additional notes about the expo event
   */
  notes?: string;

  /**
   * The owner name of the expo event
   */
  ownerName?: string;

  /**
   * The place of the expo event (legacy field)
   */
  place?: string;

  /**
   * The start date of the expo event (YYYY-MM-DD)
   */
  startDate: string;

  /**
   * The status of the expo event
   */
  status: 'PLANNED' | 'IN_PROGRESS' | 'CLOSED';

  /**
   * The town ID of the expo event
   */
  townId: string;
}
