/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStorageCaseDto {

  /**
   * The empty weight of the storage case
   */
  emptyWeightKg: number;

  /**
   * The height of the storage case in mm
   */
  heightMm: number;

  /**
   * storage case image file for the request
   */
  imageFile: Blob;

  /**
   * The length of the storage case in mm
   */
  lengthMm: number;

  /**
   * The location id of the storage case
   */
  locationId: number;

  /**
   * The manufactured on date of the storage case
   */
  manufacturedOn: string;

  /**
   * The material of the storage case
   */
  material: string;

  /**
   * The name of the storage case
   */
  name: string;

  /**
   * The observations of the storage case
   */
  observations: string;

  /**
   * The product id of the storage case
   */
  productId: number;

  /**
   * The provider id of the storage case
   */
  providerId: number;

  /**
   * The ref of the storage case
   */
  ref: string;

  /**
   * The status of the storage case
   */
  status?: 'Available' | 'AtEvent' | 'Inspecting' | 'UnderRepair' | 'Retired';

  /**
   * The type of the storage case
   */
  type: 'WOODEN_BOX' | 'PLASTIC_BOX' | 'METAL_BOX' | 'CARTON_BOX' | 'OTHER';

  /**
   * The width of the storage case in mm
   */
  widthMm: number;
}
