/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLocationDto {

  /**
   * The aisle of the location
   */
  aisle: string;

  /**
   * The level number of the location
   */
  levelNo: number;

  /**
   * The notes of the location
   */
  notes: string;

  /**
   * The position label of the location
   */
  positionLabel: string;

  /**
   * The warehouse ID of the location
   */
  warehouseId: number;
}
