/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDocumentDto {

  /**
   * The ID of the entity this document is attached to
   */
  entityId: number;

  /**
   * The type of entity this document is attached to
   */
  entityType: 'PRODUCT' | 'Repair' | 'EVENT' | 'INSPECTION' | 'CASE' | 'Podium';

  /**
   * Document file to upload (PDF, images, etc.)
   */
  file: Blob;

  /**
   * The kind/type of document
   */
  kind: 'QUOTE' | 'INVOICE' | 'PHOTO' | 'REPORT';
}
