/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTownDto {

  /**
   * Country id
   */
  countryId: number;

  /**
   * Name of the role
   */
  name: string;
}
