/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateWarehouseDto {

  /**
   * Address of the warehouse
   */
  address: string;

  /**
   * Name of the warehouse
   */
  name: string;

  /**
   * Town ID of the warehouse
   */
  townId: number;
}
