/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCountryDto {

  /**
   * The calling code of the country
   */
  callingCode: string;

  /**
   * The is un member of the country
   */
  isUnMember: boolean;

  /**
   * The iso2 of the country
   */
  iso2: string;

  /**
   * The iso3 of the country
   */
  iso3: string;

  /**
   * The long name of the country
   */
  longName: string;

  /**
   * The region of the country
   */
  regionOfWorld: string;

  /**
   * The short name of the country
   */
  shortName: string;
}
