/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateInspectionDto {

  /**
   * Comments or notes about the inspection
   */
  comments?: string;

  /**
   * Date and time of inspection
   */
  inspectedAt?: string;

  /**
   * The ID of the product being inspected (exactly one of productId or storageCaseId must be provided)
   */
  productId?: number;

  /**
   * The inspection result
   */
  result: 'OK' | 'TO_REPAIR' | 'TO_RETIRE';

  /**
   * The ID of the storage case being inspected (exactly one of productId or storageCaseId must be provided)
   */
  storageCaseId?: number;
}
