/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventStats {
  closed: number;
  inProgress: number;
  planned: number;
  total: number;
}
