/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetProviderResponse {
  active: boolean;
  address: string;
  contactName: string;
  email: string;
  id: number;
  name: string;
  phone: string;
  remarks: string;
  type: string;
}
