/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetDocumentResponse {
  createdAt: string;
  entityId: string;
  entityType: 'PRODUCT' | 'Repair' | 'EVENT' | 'INSPECTION' | 'CASE' | 'Podium';
  fileUrl: string;
  id: number;
  kind: 'QUOTE' | 'INVOICE' | 'PHOTO' | 'REPORT';
  updatedAt: string;
  uploadedAt: string;
  userId: number;
}
