/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetTransportListResponse {
  createdAt: string;
  createdBy: number;
  eventId: number;
  id: number;
  pdfUrl?: string;
  status: 'Active' | 'Archived';
  updatedAt: string;
  versionNo: number;
}
