/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GetWarehouseResponse } from '../models/get-warehouse-response';
export interface GetLocationResponseDto {
  aisle: string;
  createdAt: string;
  id: number;
  levelNo: number;
  notes: string;
  positionLabel: string;
  warehouse: GetWarehouseResponse;
}
