/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WarehouseResponse } from '../models/warehouse-response';
export interface LocationResponse {
  aisle: string;
  id: number;
  levelNo: number;
  positionLabel: string;
  site: string;
  warehouse: WarehouseResponse;
}
