/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponseDto } from '../models/user-response-dto';
export interface LoginResponseDto {
  access_token: string;
  refresh_token: string;
  user: UserResponseDto;
}
