/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginDto {

  /**
   * User email address
   */
  email: string;

  /**
   * User password
   */
  password: string;
}
