/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityTimeSeries } from '../models/activity-time-series';
import { EventStats } from '../models/event-stats';
import { InspectionStats } from '../models/inspection-stats';
import { MovementStats } from '../models/movement-stats';
import { ProductStatusStats } from '../models/product-status-stats';
import { RepairStats } from '../models/repair-stats';
import { TransportListStats } from '../models/transport-list-stats';
export interface OverviewStatisticsDto {
  activityTimeSeries: Array<ActivityTimeSeries>;
  eventStats: EventStats;
  inspectionStats: InspectionStats;
  movementStats: MovementStats;
  productStatusStats: ProductStatusStats;
  repairStats: RepairStats;
  totalEvents: number;
  totalInspections: number;
  totalMovements: number;
  totalProducts: number;
  totalProviders: number;
  totalRepairs: number;
  totalTransportLists: number;
  totalWarehouses: number;
  transportListStats: TransportListStats;
}
