/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponseDto } from '../models/user-response-dto';
export interface PaginatedUserResponseDto {
  data: Array<UserResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
