/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductStatusStats {
  atEvent: number;
  available: number;
  inspecting: number;
  retired: number;
  underRepair: number;
}
