/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocationResponse } from '../models/location-response';
import { ProductCategoryResponse } from '../models/product-category-response';
import { ProductFileResponse } from '../models/product-file-response';
import { ProviderResponse } from '../models/provider-response';
export interface ProductResponse {
  category: ProductCategoryResponse;
  createdAt: string;
  description: string;
  entryDate: string;
  files: Array<ProductFileResponse>;
  hasBattery?: boolean;
  heightMm: number;
  id: number;
  imageFile?: ProductFileResponse;
  lengthMm: number;
  location: LocationResponse;
  name: string;
  price?: number;
  isElectricalDevice?: boolean;
  provider: ProviderResponse;
  ref: string;
  specFile?: ProductFileResponse;
  storageCaseStatus?: string;
  status: string;
  updatedAt: string;
  weightKg: number;
  widthMm: number;
}
