/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductFileResponse {
  fileType: string;
  fileUrl: string;
  id: number;
  originalName: string;
  purpose: string;
}
