/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefreshTokenDto {

  /**
   * Refresh token to exchange for a new access token
   */
  refreshToken: string;
}
