/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ToggleActivationDto {

  /**
   * Whether to deactivate (true) or activate (false) the staff member
   */
  isDeactivated: boolean;
}
