/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CountryResponse } from '../models/country-response';
export interface TownResponse {

  /**
   * Country of the town
   */
  country: CountryResponse;

  /**
   * ID of the town
   */
  id: number;

  /**
   * Name of the town
   */
  name: string;
}
