/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRole } from '../models/user-role';
export interface UpdateStaffMultipartDto {

  /**
   * Email
   */
  email: string;

  /**
   * First name
   */
  firstName: string;

  /**
   * Last name
   */
  lastName?: string;

  /**
   * Phone number
   */
  phoneNumber: string;

  /**
   * Profile picture image file (JPEG, PNG, WebP)
   */
  profilePicture?: Blob;

  /**
   * Role code - Select user role from the dropdown
   */
  roleCode: UserRole;
}
