/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePodiumDto {

  /**
   * The height of the podium in mm
   */
  heightMm?: number;

  /**
   * Podium image file for the request
   */
  imageFile?: Blob;

  /**
   * The length of the podium in mm
   */
  lengthMm?: number;

  /**
   * The location id of the podium
   */
  locationId?: number;

  /**
   * The name of the podium
   */
  name?: string;

  /**
   * The observations of the podium
   */
  observations?: string;

  /**
   * The ref of the podium
   */
  ref?: string;

  /**
   * The width of the podium in mm
   */
  widthMm?: number;
}
