/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProductDto {

  /**
   * category
   */
  categoryId?: number;

  /**
   * description
   */
  description?: string;

  /**
   * entryDate
   */
  entryDate?: string;

  /**
   * heightMm
   */
  heightMm?: number;

  /**
   * Product image file for backward compatibility
   */
  imageFile?: Blob;

  /**
   * Product image files for the request (multiple allowed)
   */
  imageFiles?: Array<Blob>;

  /**
   * lengthMm
   */
  lengthMm?: number;

  /**
   * Location id
   */
  locationId?: number;

  /**
   * name
   */
  name?: string;

  /**
   * Provider id
   */
  providerId?: number;

  /**
   * price
   */
  price?: number;

  /**
   * Ref of the product
   */
  ref?: string;

  /**
   * Product specification sheet file (PDF)
   */
  specSheetFile?: Blob;

  /**
   * status
   */
  status?: 'Available' | 'AtEvent' | 'Inspecting' | 'UnderRepair' | 'Retired';

  /**
   * weightKg
   */
  weightKg?: number;

  /**
   * widthMm
   */
  widthMm?: number;
}
