/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTownDto {

  /**
   * Country id
   */
  countryId?: number;

  /**
   * Name of the role
   */
  name?: string;
}
