/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateConsumableDto {

  /**
   * The category of the consumable
   */
  category?: 'Accessories' | 'Tools' | 'Materials' | 'Other';

  /**
   * The event id of the consumable
   */
  eventId?: number;

  /**
   * Image file for the consumable
   */
  imageFile?: Blob;

  /**
   * The name of the consumable
   */
  name?: string;

  /**
   * The notes of the consumable
   */
  notes?: string;

  /**
   * The product id of the consumable
   */
  productId?: number;

  /**
   * The provider id of the consumable
   */
  providerId?: number;

  /**
   * purchased Date
   */
  purchasedAt?: string;

  /**
   * The quantity of the consumable
   */
  quantity?: number;

  /**
   * The unit of mesurement of the consumable
   */
  unit?: string;

  /**
   * The unit cost of the consumable
   */
  unitCost?: number;
}
