/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserRoleDto {

  /**
   * Code of the role
   */
  code: string;

  /**
   * Description of the role
   */
  description: string;

  /**
   * Name of the role
   */
  name: string;
}
