/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProductCategoryDto {

  /**
   * Code of the product category
   */
  code?: string;

  /**
   * Description of the product category
   */
  description?: string;

  /**
   * Name of the product category
   */
  name?: string;
}
