/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTransportItemDto {

  /**
   * Additional notes about this transport item
   */
  notes?: string;

  /**
   * The ID of the product to transport
   */
  productId?: number;

  /**
   * The ID of the transport list this item belongs to
   */
  transportListId?: number;
}
