/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTransportPodiumDto {

  /**
   * Gross weight in kg (optional, can be calculated)
   */
  grossWeightKg?: number;

  /**
   * Additional notes about this transport podium
   */
  notes?: string;

  /**
   * The ID of the podium to transport
   */
  podiumId?: number;

  /**
   * The ID of the transport list this podium belongs to
   */
  transportListId?: number;
}
