/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UploadedFileResponseDto {

  /**
   * The file type of the uploaded file
   */
  fileType: string;

  /**
   * Image url
   */
  fileUrl: string;

  /**
   * The id of the uploaded file
   */
  id: number;

  /**
   * The user id of the uploaded file
   */
  userId: number;
}
