/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Role code - Select user role from the dropdown
 */
export enum UserRole {
  Admin = 'ADMIN',
  AlphaStoreManager = 'ALPHA_STORE_MANAGER',
  Marketer = 'MARKETER',
  LogisticManager = 'LOGISTIC_MANAGER'
}
