/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTransportPodiumDto } from '../../models/create-transport-podium-dto';
import { TransportPodium } from '../../models/transport-podium';

export interface TransportPodiumControllerCreateV1$Params {
      body: CreateTransportPodiumDto
}

export function transportPodiumControllerCreateV1(http: HttpClient, rootUrl: string, params: TransportPodiumControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportPodium>> {
  const rb = new RequestBuilder(rootUrl, transportPodiumControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransportPodium>;
    })
  );
}

transportPodiumControllerCreateV1.PATH = '/api/v1/transport-podium';
