/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransportPodium } from '../../models/transport-podium';
import { UpdateTransportPodiumDto } from '../../models/update-transport-podium-dto';

export interface TransportPodiumControllerUpdateV1$Params {
  id: number;
      body: UpdateTransportPodiumDto
}

export function transportPodiumControllerUpdateV1(http: HttpClient, rootUrl: string, params: TransportPodiumControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportPodium>> {
  const rb = new RequestBuilder(rootUrl, transportPodiumControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TransportPodium>;
    })
  );
}

transportPodiumControllerUpdateV1.PATH = '/api/v1/transport-podium/{id}';
