/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Inspection } from '../../models/inspection';
import { UpdateInspectionDto } from '../../models/update-inspection-dto';

export interface InspectionControllerUpdateV1$Params {
  id: number;
      body: UpdateInspectionDto
}

export function inspectionControllerUpdateV1(http: HttpClient, rootUrl: string, params: InspectionControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Inspection>> {
  const rb = new RequestBuilder(rootUrl, inspectionControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Inspection>;
    })
  );
}

inspectionControllerUpdateV1.PATH = '/api/v1/inspection/{id}';
