/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Inspection } from '../../models/inspection';

export interface InspectionControllerFindOneV1$Params {
  id: number;
}

export function inspectionControllerFindOneV1(http: HttpClient, rootUrl: string, params: InspectionControllerFindOneV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Inspection>> {
  const rb = new RequestBuilder(rootUrl, inspectionControllerFindOneV1.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Inspection>;
    })
  );
}

inspectionControllerFindOneV1.PATH = '/api/v1/inspection/{id}';
