/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Inspection } from '../../models/inspection';

export interface InspectionControllerFindAllV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by product ID
 */
  productId?: number;

/**
 * Filter by storage case ID
 */
  storageCaseId?: number;

/**
 * Filter by inspection result
 */
  result?: 'OK' | 'TO_REPAIR' | 'TO_RETIRE';
}

export function inspectionControllerFindAllV1(http: HttpClient, rootUrl: string, params?: InspectionControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Inspection>>> {
  const rb = new RequestBuilder(rootUrl, inspectionControllerFindAllV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('productId', params.productId, {});
    rb.query('storageCaseId', params.storageCaseId, {});
    rb.query('result', params.result, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Inspection>>;
    })
  );
}

inspectionControllerFindAllV1.PATH = '/api/v1/inspection';
