/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Consumable } from '../../models/consumable';

export interface ConsumableControllerRemoveV1$Params {
  id: number;
}

export function consumableControllerRemoveV1(http: HttpClient, rootUrl: string, params: ConsumableControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Consumable>> {
  const rb = new RequestBuilder(rootUrl, consumableControllerRemoveV1.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Consumable>;
    })
  );
}

consumableControllerRemoveV1.PATH = '/api/v1/consumable/{id}';
