/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConsumableCategory } from '../../models/consumable-category';
import { GetConsumableResponse } from '../../models/get-consumable-response';

export interface ConsumableControllerGetAllConsumablesV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Name of the Consumable
 */
  name?: string;
  category?: ConsumableCategory;

/**
 * providerId of the Consumable
 */
  providerId?: number;

/**
 * productId  of the Consumable
 */
  productId?: number;

/**
 * eventId number of the Consumable
 */
  eventId?: number;

/**
 * Purchase date of the Consumable
 */
  purchasedAt?: string;

/**
 * Notes of the location
 */
  notes?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc' | 'name:asc' | 'category:asc' | 'category:desc' | 'providerId:asc' | 'providerId:desc' | 'productId:asc' | 'productId:desc' | 'eventId:asc' | 'eventId:desc' | 'purchasedAt:asc' | 'purchasedAt:desc' | 'notes:asc' | 'notes:desc';
}

export function consumableControllerGetAllConsumablesV1(http: HttpClient, rootUrl: string, params?: ConsumableControllerGetAllConsumablesV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetConsumableResponse>>> {
  const rb = new RequestBuilder(rootUrl, consumableControllerGetAllConsumablesV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('name', params.name, {});
    rb.query('category', params.category, {});
    rb.query('providerId', params.providerId, {});
    rb.query('productId', params.productId, {});
    rb.query('eventId', params.eventId, {});
    rb.query('purchasedAt', params.purchasedAt, {});
    rb.query('notes', params.notes, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetConsumableResponse>>;
    })
  );
}

consumableControllerGetAllConsumablesV1.PATH = '/api/v1/consumable';
