/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorageCase } from '../../models/storage-case';
import { UpdateStorageCaseDto } from '../../models/update-storage-case-dto';

export interface StorageCaseControllerUpdateV1$Params {
  id: number;
      body: UpdateStorageCaseDto
}

export function storageCaseControllerUpdateV1(http: HttpClient, rootUrl: string, params: StorageCaseControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageCase>> {
  const rb = new RequestBuilder(rootUrl, storageCaseControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StorageCase>;
    })
  );
}

storageCaseControllerUpdateV1.PATH = '/api/v1/storage-case/{id}';
