/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetStorageCaseResponseDto } from '../../models/get-storage-case-response-dto';

export interface StorageCaseControllerGetAllStorageCasesV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * The ref of the storage case
 */
  ref?: string;

/**
 * The length of the podium in mm
 */
  lengthMm?: number;

/**
 * The width of the podium in mm
 */
  widthMm?: number;

/**
 * The height of the podium in mm
 */
  heightMm?: number;

/**
 * The status of the storage case
 */
  status?: 'Available' | 'AtEvent' | 'Inspecting' | 'UnderRepair' | 'Retired';

/**
 * The location id of the storage case
 */
  locationId?: number;

/**
 * The observations of the storage case
 */
  observations?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc';
}

export function storageCaseControllerGetAllStorageCasesV1(http: HttpClient, rootUrl: string, params?: StorageCaseControllerGetAllStorageCasesV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetStorageCaseResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, storageCaseControllerGetAllStorageCasesV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('ref', params.ref, {});
    rb.query('lengthMm', params.lengthMm, {});
    rb.query('widthMm', params.widthMm, {});
    rb.query('heightMm', params.heightMm, {});
    rb.query('status', params.status, {});
    rb.query('locationId', params.locationId, {});
    rb.query('observations', params.observations, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetStorageCaseResponseDto>>;
    })
  );
}

storageCaseControllerGetAllStorageCasesV1.PATH = '/api/v1/storage-case';
