/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateStorageCaseDto } from '../../models/create-storage-case-dto';
import { StorageCase } from '../../models/storage-case';

export interface StorageCaseControllerCreateV1$Params {
      body: CreateStorageCaseDto
}

export function storageCaseControllerCreateV1(http: HttpClient, rootUrl: string, params: StorageCaseControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageCase>> {
  const rb = new RequestBuilder(rootUrl, storageCaseControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StorageCase>;
    })
  );
}

storageCaseControllerCreateV1.PATH = '/api/v1/storage-case';
