/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Provider } from '../../models/provider';
import { UpdateProviderDto } from '../../models/update-provider-dto';

export interface ProviderControllerUpdateV1$Params {
  id: number;
      body: UpdateProviderDto
}

export function providerControllerUpdateV1(http: HttpClient, rootUrl: string, params: ProviderControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Provider>> {
  const rb = new RequestBuilder(rootUrl, providerControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Provider>;
    })
  );
}

providerControllerUpdateV1.PATH = '/api/v1/provider/{id}';
