/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetProviderResponse } from '../../models/get-provider-response';

export interface ProviderControllerGetAllProvidersV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;
  name?: string;
  type?: string;
  contactName?: string;
  email?: string;
  phone?: string;
  address?: string;
  remarks?: string;
  active?: boolean;
}

export function providerControllerGetAllProvidersV1(http: HttpClient, rootUrl: string, params?: ProviderControllerGetAllProvidersV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetProviderResponse>>> {
  const rb = new RequestBuilder(rootUrl, providerControllerGetAllProvidersV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('name', params.name, {});
    rb.query('type', params.type, {});
    rb.query('contactName', params.contactName, {});
    rb.query('email', params.email, {});
    rb.query('phone', params.phone, {});
    rb.query('address', params.address, {});
    rb.query('remarks', params.remarks, {});
    rb.query('active', params.active, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetProviderResponse>>;
    })
  );
}

providerControllerGetAllProvidersV1.PATH = '/api/v1/provider';
