/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateProviderDto } from '../../models/create-provider-dto';
import { Provider } from '../../models/provider';

export interface ProviderControllerCreateV1$Params {
      body: CreateProviderDto
}

export function providerControllerCreateV1(http: HttpClient, rootUrl: string, params: ProviderControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Provider>> {
  const rb = new RequestBuilder(rootUrl, providerControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Provider>;
    })
  );
}

providerControllerCreateV1.PATH = '/api/v1/provider';
