/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateWarehouseDto } from '../../models/create-warehouse-dto';
import { GetWarehouseResponse } from '../../models/get-warehouse-response';

export interface WarehouseControllerCreateV1$Params {
  
    /**
     * Create warehouse request body
     */
    body: CreateWarehouseDto
}

export function warehouseControllerCreateV1(http: HttpClient, rootUrl: string, params: WarehouseControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetWarehouseResponse>> {
  const rb = new RequestBuilder(rootUrl, warehouseControllerCreateV1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetWarehouseResponse>;
    })
  );
}

warehouseControllerCreateV1.PATH = '/api/v1/warehouse';
