/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetWarehouseResponse } from '../../models/get-warehouse-response';

export interface WarehouseControllerFindAllV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Name of the warehouse
 */
  name?: string;

/**
 * Address of the warehouse
 */
  address?: string;

/**
 * Sort order (field:direction)
 */
  orderBy?: 'createdAt:asc' | 'createdAt:desc';
}

export function warehouseControllerFindAllV1(http: HttpClient, rootUrl: string, params?: WarehouseControllerFindAllV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetWarehouseResponse>>> {
  const rb = new RequestBuilder(rootUrl, warehouseControllerFindAllV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('name', params.name, {});
    rb.query('address', params.address, {});
    rb.query('orderBy', params.orderBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetWarehouseResponse>>;
    })
  );
}

warehouseControllerFindAllV1.PATH = '/api/v1/warehouse';
