/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetWarehouseResponse } from '../../models/get-warehouse-response';
import { UpdateWarehouseDto } from '../../models/update-warehouse-dto';

export interface WarehouseControllerUpdateV1$Params {
  id: number;
  
    /**
     * Update warehouse request body
     */
    body: UpdateWarehouseDto
}

export function warehouseControllerUpdateV1(http: HttpClient, rootUrl: string, params: WarehouseControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<GetWarehouseResponse>> {
  const rb = new RequestBuilder(rootUrl, warehouseControllerUpdateV1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetWarehouseResponse>;
    })
  );
}

warehouseControllerUpdateV1.PATH = '/api/v1/warehouse/{id}';
