/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetDocumentResponse } from '../../models/get-document-response';

export interface DocumentControllerFindByEntityV1$Params {
  entityType: string;
  entityId: number;
}

export function documentControllerFindByEntityV1(http: HttpClient, rootUrl: string, params: DocumentControllerFindByEntityV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetDocumentResponse>>> {
  const rb = new RequestBuilder(rootUrl, documentControllerFindByEntityV1.PATH, 'get');
  if (params) {
    rb.path('entityType', params.entityType, {});
    rb.path('entityId', params.entityId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetDocumentResponse>>;
    })
  );
}

documentControllerFindByEntityV1.PATH = '/api/v1/document/entity/{entityType}/{entityId}';
