/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetDocumentResponse } from '../../models/get-document-response';

export interface DocumentControllerGetAllDocumentsV1$Params {

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  limit?: number;

/**
 * Filter by document kind
 */
  kind?: 'QUOTE' | 'INVOICE' | 'PHOTO' | 'REPORT';

/**
 * Filter by entity type
 */
  entityType?: 'PRODUCT' | 'Repair' | 'EVENT' | 'INSPECTION' | 'CASE' | 'Podium';

/**
 * Filter by entity ID
 */
  entityId?: number;

/**
 * Filter by user ID (uploader)
 */
  userId?: number;
}

export function documentControllerGetAllDocumentsV1(http: HttpClient, rootUrl: string, params?: DocumentControllerGetAllDocumentsV1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetDocumentResponse>>> {
  const rb = new RequestBuilder(rootUrl, documentControllerGetAllDocumentsV1.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('kind', params.kind, {});
    rb.query('entityType', params.entityType, {});
    rb.query('entityId', params.entityId, {});
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetDocumentResponse>>;
    })
  );
}

documentControllerGetAllDocumentsV1.PATH = '/api/v1/document';
